@startuml
MainWindow -> MainWindow : load()
activate MainWindow
note right: User selects project file
MainWindow -> MainWindow : Extract data.json
loop over files in ZIPfile
    alt file is image
        MainWindow -> MainWindow : Extract image to /tmp directory
        MainWindow -> TextureList : Add texture
    end
end
MainWindow -> MainWindow : Extract settings from data.json
MainWindow -> Settings : restore(settings)
activate Settings
Settings -> MainWindow : Done
deactivate Settings
MainWindow -> Nodeeditor : restore(data)
note right: Restore node data from data.json 
activate Nodeeditor
Nodeeditor -> "QtNodes::FlowScene" : restore(data)
activate "QtNodes::FlowScene"
loop over Node data
    "QtNodes::FlowScene" -> Node : Create node
    note right: Nodes run\ngeneration\nas needed
    "QtNodes::FlowScene" -> Node : restore(node data)
end
"QtNodes::FlowScene" -> Nodeeditor : Done
deactivate "QtNodes::FlowScene"
Nodeeditor -> MainWindow : Done
deactivate Nodeeditor
deactivate MainWindow
@enduml