Terrain Generator: Terrain Class Reference
Terrain Class Reference
#include <terrain.h>
Public Member Functions
Terrain (int resolution)
void setResolution (int resolution)
void initializeGL ()
void paintGL (QOpenGLFunctions *f, QMatrix4x4 camera_matrix, QVector3D camera_pos, QVector3D light_color, QVector3D light_pos, float light_intensity, QVector3D ambient)
void setHeightMap (QImage height_map)
void setNormalMap (QImage normal_map)
void setAlbedoMap (QImage albedo_map)
void setDrawLines (bool lines)
void setTerrainColor (QColor color)
void setLineColor (QColor color)
bool drawLines ()
QColor terrainColor ()
QColor lineColor ()
Private Member Functions
void _paintGL (QOpenGLFunctions *f, QMatrix4x4 camera_matrix, QVector3D camera_pos, QVector3D light_color, QVector3D light_pos, float light_intensity, QVector3D color, QVector3D ambient, bool lines_mode=false)
Private Attributes
bool _draw_lines = false
QVector3D _terrain_color {0.75f, 0.75f, 0.75f}
QVector3D _line_color {1.0f, 1.0f, 1.0f}
QMatrix4x4 _transform
QVector< GLfloat > _vertices
QVector< GLushort > _indexes
QOpenGLVertexArrayObject _vao
QOpenGLBuffer _vertex_buffer {QOpenGLBuffer::VertexBuffer}
QOpenGLShaderProgram _program
QOpenGLTexture * _height
QOpenGLTexture * _normal
QOpenGLTexture * _albedo
Detailed Description
Terrain
Class manages the terrain mesh and is used to set the shader parameters and set the height and normal map.
Constructor & Destructor Documentation
Terrain()
Terrain::Terrain (int resolution)
Terrain
Create the terrain handler class with the set resolution of vertices along an edge. Total vertices are resolution squared.
Parameters
int resolution : The size of the vertices along a single edge.
Member Function Documentation
_paintGL()
void Terrain::_paintGL (QOpenGLFunctions * f, QMatrix4x4 camera_matrix, QVector3D camera_pos, QVector3D light_color, QVector3D light_pos, float light_intensity, QVector3D color, QVector3D ambient, bool lines_mode = false) private
_paintGl
Draw the terrain to the opengl widget. With a toggle whether to draw lines or the terrain.
Parameters
QOpenGLFunctions* f : The valid opengl functions.
QMatrix4x4 camera_matrix : The combined view and projection matrices.
QVector3D camera_pos : The camera's position in world space.
QVector3D light_color : The suns colour.
QVector3D light_pos : The position of the sun.
float light_intensity : The intensity of the light.
QVector3D ambient : The sky colour/ambient light colour.
bool lines_mode : Whether or not to draw lines or the terrain.
Referenced by paintGL().
drawLines()
bool Terrain::drawLines ()
drawLines
Get whether or not we are drawing lines.
Returns
bool : Whether or not to draw lines.
Referenced by OpenGL::terrainDrawLines().
initializeGL()
void Terrain::initializeGL ()
initializeGL
Initialize the opengl functionality of the terrain. Create and attach shaders textures, and vertex buffers.
Referenced by OpenGL::initializeGL().
lineColor()
QColor Terrain::lineColor ()
lineColor
Get the current line colour.
Returns
QColor : The line colour.
Referenced by OpenGL::terrainLineColor().
paintGL()
void Terrain::paintGL (QOpenGLFunctions * f, QMatrix4x4 camera_matrix, QVector3D camera_pos, QVector3D light_color, QVector3D light_pos, float light_intensity, QVector3D ambient)
paintGl
Draw the terrain to the opengl widget.
Parameters
QOpenGLFunctions* f : The valid opengl functions.
QMatrix4x4 camera_matrix : The combined view and projection matrices.
QVector3D camera_pos : The camera's position in world space.
QVector3D light_color : The suns colour.
QVector3D light_pos : The position of the sun.
float light_intensity : The intensity of the light.
QVector3D ambient : The sky colour/ambient light colour.
Referenced by OpenGL::paintGL().
setAlbedoMap()
void Terrain::setAlbedoMap (QImage albedo_map)
setAlbedoMap
Set the albedo map image.
Parameters
QImage albedo_map : The albedo map image.
Referenced by OpenGL::nodeeditorOutputUpdated().
setDrawLines()
void Terrain::setDrawLines (bool lines)
setDrawLines
Set whether or not to draw texture lines.
Parameters
bool lines : Wether or not to draw lines.
Referenced by OpenGL::setTerrainDrawLines().
setHeightMap()
void Terrain::setHeightMap (QImage height_map)
setHeightMap
Set the height map image.
Parameters
QImage height_map : The height map image.
Referenced by OpenGL::nodeeditorOutputUpdated().
setLineColor()
void Terrain::setLineColor (QColor color)
setLineColor
Set the colour of the terrain lines.
Parameters
QColor color : The colour of the lines.
Referenced by OpenGL::setTerrainLineColor().
setNormalMap()
void Terrain::setNormalMap (QImage normal_map)
setNormalMap
Set the normal map image.
Parameters
QImage normal_map : The normal map image.
Referenced by OpenGL::nodeeditorOutputUpdated().
setResolution()
void Terrain::setResolution (int resolution)
setResolution
Sets the resolution of the mesh along an edge.
Parameters
int resolution : The new resolution of the mesh.
Referenced by OpenGL::setTerrainMeshResolution(), and Terrain().
setTerrainColor()
void Terrain::setTerrainColor (QColor color)
setTerrainColor
Set the colour of the terrain.
Parameters
QColor color : The colour of the terrain.
Referenced by OpenGL::setTerrainColor().
terrainColor()
QColor Terrain::terrainColor ()
terrainColor
Get the current colour of the terrai.
Referenced by OpenGL::terrainColor().
The documentation for this class was generated from the following files:
src/OpenGL/terrain.h
src/OpenGL/terrain.cpp