Terrain Generator: Camera Class Reference
Camera Class Reference
#include <camera.h>
Public Member Functions
QMatrix4x4 matrix ()
QMatrix4x4 rotationMatrix ()
QMatrix4x4 projectionMatrix ()
QVector3D position ()
float rotateY (float value)
float rotateX (float value)
float zoom (float value)
float zoom ()
float setRotationY (float value)
float setRotationX (float value)
float setZoom (float value)
void resize (int w, int h)
float rotationX ()
float rotationY ()
Private Member Functions
QMatrix4x4 _matrix ()
void _clampRotationX ()
Private Attributes
float _rotation_x = 0.0f
float _rotation_y = 0.0f
float _zoom = 1.0f
float _projection = 1.0f
Detailed Description
Camera
Houses the projection matrix and the view matrix. Used to changed the values for the generation of said matrices. Can return the current rotations of the camera, the zoom, and the position of the camera in world space.
Member Function Documentation
_clampRotationX()
void Camera::_clampRotationX () private
_clampRotationX
Clamps the rotation over the the terrain between 0 and 90 degrees.
Referenced by rotateX(), and setRotationX().
_matrix()
QMatrix4x4 Camera::_matrix () private
_matrix
Returns the calculated view matrix only.
Returns
QMatrix4x4 : The view matrix.
Referenced by matrix(), and position().
matrix()
QMatrix4x4 Camera::matrix ()
matrix
Returns the combined view and projection matrix.
Returns
QMatrix4x4 : The combined view and projection matrices.
Referenced by OpenGL::paintGL().
position()
QVector3D Camera::position ()
position
Returns the position of the camera in 3D world space.
Returns
QVector3D : The position of the camera.
Referenced by OpenGL::paintGL().
projectionMatrix()
QMatrix4x4 Camera::projectionMatrix ()
projectionMatrix
Returns the projection matrix only.
Returns
QMatrix4x4 : The projection matrix.
Referenced by matrix().
resize()
void Camera::resize (int w, int h)
resize
Resize the camera and recalculates the projection ration used for the projection matrix.
Parameters
int w : The width of the viewport.
int h : The height of the viewport.
Referenced by OpenGL::resizeGL().
rotateX()
float Camera::rotateX (float value)
rotateX
Rotates the camera over the terrain. The new current rotation is returned (rotation is clamped between 0 and 89).
Parameters
float value : The value to rotate by.
Returns
float : The new rotation value.
Referenced by OpenGL::mouseMoveEvent().
rotateY()
float Camera::rotateY (float value)
rotateY
Rotates the camera about the terrain (turntable style). The new current rotation is returned (rotation is clamped between 0 and 359).
Parameters
float value : The value to rotate by.
Returns
float : The new rotation value.
Referenced by OpenGL::mouseMoveEvent().
rotationMatrix()
QMatrix4x4 Camera::rotationMatrix ()
rotationMatrix
Returns the rotation matrix, the rotations along the x- and y-axis and not the projections or the view. This is used for the decals that should only be rotated on screen as a flat image and not in 3D space.
Returns
QMatrix4x4 : The rotation matrix.
Referenced by OpenGL::paintGL().
rotationX()
float Camera::rotationX ()
rotationX
Returns the current rotation of the x value.
Returns
float : The current rotation.
rotationY()
float Camera::rotationY ()
rotationY
Returns the current rotation of the y value.
Returns
float : The current rotation.
setRotationX()
float Camera::setRotationX (float value)
setRotationX
Sets the rotation x value, overriding the previous value rather than adding onto it. The value is clamped between 0 and 90.
Parameters
float value : The value to set the rotation to.
Returns
float : The new value.
Referenced by OpenGL::camRotationX(), and OpenGL::OpenGL().
setRotationY()
float Camera::setRotationY (float value)
setRotationY
Sets the rotation y value, overriding the previous value rather than adding onto it.
Parameters
float value : The value to set the rotation to.
Returns
float : The new value.
Referenced by OpenGL::camRotationY(), and OpenGL::OpenGL().
setZoom()
float Camera::setZoom (float value)
setZoom
Sets the zoom value overriding the current value rather than adding to it.
Parameters
float value : The value to set the zoom to.
Returns
float : The new zoom value.
Referenced by OpenGL::camZoom(), and OpenGL::OpenGL().
zoom() [1/2]
float Camera::zoom (float value)
zoom
Zooms into and out of the terrain along a track from the current camera's position and the world origin. The zoom is clamped between 1 and 20.
Parameters
float value : The value to zoom by.
Returns
float : The new zoom value.
Referenced by OpenGL::wheelEvent().
zoom() [2/2]
float Camera::zoom ()
zoom
Get the current zoom value.
Returns
float : The current zoom value.
The documentation for this class was generated from the following files:
src/OpenGL/camera.h
src/OpenGL/camera.cpp