Terrain Generator: BezierFactory Class Reference
BezierFactory Class Reference
#include <bezierwidget.h>
Public Member Functions
BezierFactory (QGraphicsScene *s)
BezierFactory (QPen l_pen, QPen c_pen, QBrush c_brush, QPen e_pen, QBrush e_brush, QPen cu_pen, float r=3.0f, float c_thick=0.25f, float l_width=0.5f, float c_width=1.0f, QGraphicsScene *s=nullptr)
Bezier newBezier (QPointF c_0, QPointF c_1, QGraphicsEllipseItem *e_0, QGraphicsEllipseItem *e_1)
QGraphicsEllipseItem * newEllipse (QPointF pos)
Public Attributes
QGraphicsScene * scene = nullptr
QPen line_pen
QPen control_pen
QBrush control_brush
QPen end_pen
QBrush end_brush
QPen curve_pen
float radius = 8.0f
float control_thick = 0.25f
float line_width = 0.5f
float curve_width = 1.0f
Detailed Description
BezierFactory
Factory class for creating Bezier objects that ensures the entirety of the overall bezier curve is drawn with the same stylings.
Constructor & Destructor Documentation
BezierFactory() [1/2]
BezierFactory::BezierFactory (QGraphicsScene * s)
BezierFactory
Creates the default factory with the default values.
Parameters
QGraphicsScene* s : The reference scene for curves to draw on.
BezierFactory() [2/2]
BezierFactory::BezierFactory (QPen l_pen, QPen c_pen, QBrush c_brush, QPen e_pen, QBrush e_brush, QPen cu_pen, float r = 3.0f, float c_thick = 0.25f, float l_width = 0.5f, float c_width = 1.0f, QGraphicsScene * s = nullptr)
BezierFactory
Creates a new bezier factory with the overriden values.
Parameters
QPen l_pen : The line pen (between control and end point).
QPen c_pen : The control pen (outline on a control circle).
QBrush c_brush : The control brush (fill).
QPen e_pen : The end point pen (outline).
QBrush e_brush : The end point brush (fill).
QPen cu_pen : The curve pen (the bezier curve itself)
float r : The radius of the control and end point circles.
float c_thick : The control and end point outline thickness.
float l_width : The width of the lines between control and end point.
float c_width : The width of the lines that make up the curve.
QGraphicsScene* s : The scene that draws the elements
Member Function Documentation
newBezier()
Bezier BezierFactory::newBezier (QPointF c_0, QPointF c_1, QGraphicsEllipseItem * e_0, QGraphicsEllipseItem * e_1)
newBezier
Creates a new bezier with the internal stylings of the factory.
Parameters
QPointF c_0 : The first control point.
QPointF c_1 : The second control point.
QGraphicsEllipseItem* e_0 : The pointer to the first end point.
QGraphicsEllipseItem* e_1 : The pointer to the second end point.
Returns
Bezier : The newly created bezier.
Referenced by BezierEditWidget::BezierEditWidget(), and BezierEditWidget::restore().
newEllipse()
QGraphicsEllipseItem * BezierFactory::newEllipse (QPointF pos)
newEllipse
From a point the new ellipse is created using internal values.
Parameters
QPointF pos : The position of the new ellipse.
Returns
QGraphicsEllipseItem* : The pointer to the new ellipse item.
Referenced by BezierEditWidget::BezierEditWidget(), and BezierEditWidget::restore().
The documentation for this class was generated from the following files:
src/Nodeeditor/Nodes/BezierCurveWidget/bezierwidget.h
src/Nodeeditor/Nodes/BezierCurveWidget/bezierwidget.cpp