Terrain Generator: ConverterClampNode Class Reference
ConverterClampNode Class Reference
#include <clamp.h>
Public Types
enum Mode { CLAMP, SIGMOID }
Public Slots
void inputConnectionDeleted (QtNodes::Connection const &connection)
Public Member Functions
ConverterClampNode ()
void created () override
QString caption () const override
QString name () const override
QWidget * embeddedWidget ()
QWidget * sharedWidget ()
unsigned int nPorts (QtNodes::PortType port_type) const override
QtNodes::NodeDataType dataType (QtNodes::PortType port_type, QtNodes::PortIndex port_index) const override
QJsonObject save () const override
void restore (QJsonObject const &data) override
std::shared_ptr< QtNodes::NodeData > outData (QtNodes::PortIndex port)
void setInData (std::shared_ptr< QtNodes::NodeData > node_data, QtNodes::PortIndex port)
virtual bool hasShared ()
Static Public Member Functions
static double clamp (double v, double min, double max)
static double sigmoid (double v, double min, double max)
Private Member Functions
void _generate ()
Private Attributes
IntensityMap _output {1, 1, 1.00}
ConverterClampNode::Mode _mode = ConverterClampNode::CLAMP
std::shared_ptr< IntensityMapData > _input
std::shared_ptr< IntensityMapData > _input_min
std::shared_ptr< IntensityMapData > _input_max
double _min = 0.00
double _max = 1.00
bool _set = false
bool _set_min = false
bool _set_max = false
Ui::ClampNode _ui
Ui::ClampNode _shared_ui
QWidget * _widget
QWidget * _shared_widget
Friends
class ConverterClampNode_Test
Detailed Description
ConverterClampNode
Node that clamps an input intensity map by restricting the range of values between a MIN and MAX value. The user can select either a hard clamp that truncates values beyond the bounds of the range or a smooth clamp using a sigmoid function.
Constructor & Destructor Documentation
ConverterClampNode()
ConverterClampNode::ConverterClampNode ()
ConverterClampNode
Creates a clamping node attaching the UI.
Member Function Documentation
_generate()
void ConverterClampNode::_generate () private
_generate
Generates the output data from the supplied and available data.
dataUpdated
Referenced by inputConnectionDeleted(), and setInData().
caption()
QString ConverterClampNode::caption () const override
caption
Return a string that is displayed on the node and in the properties.
Returns
QString : The caption.
clamp()
double ConverterClampNode::clamp (double v, double min, double max) static
clamp
Algorithm to truncate values beyond the min and max value to min or max respectively.
Parameters
double v : The value to be truncated.
double min : The minimum value.
double max : The maximum value.
Returns
double : The truncated value.
Referenced by _generate().
created()
void ConverterClampNode::created () override virtual
created
Function is called when the node is created so it can connect to listeners.
Reimplemented from Node.
dataType()
QtNodes::NodeDataType ConverterClampNode::dataType (QtNodes::PortType port_type, QtNodes::PortIndex port_index) const override
dataType
Returns the data type for each of the ports.
Parameters
QtNodes::PortType port_type : The type of port (in or out).
QtNodes::PortIndex port_index : The port index on each side.
Returns
QtNodes::NodeDataType : The type of data the port provides/accepts.
embeddedWidget()
QWidget * ConverterClampNode::embeddedWidget ()
embeddedWidget
Returns a pointer to the widget that gets embedded within the node in the dataflow diagram.
Returns
QWidget* : The embedded widget.
inputConnectionDeleted
void ConverterClampNode::inputConnectionDeleted (QtNodes::Connection const & connection) slot
inputConnectionDeleted
Called when an input connection is deleted, this usually resets some data and regenerates the output data.
Parameters
QtNodes::Connection const& connection : The connection being deleted.
dataUpdated
name()
QString ConverterClampNode::name () const override
name
Return a string that is displayed in the node selection list.
Returns
QString : The name.
Referenced by save().
nPorts()
unsigned int ConverterClampNode::nPorts (QtNodes::PortType port_type) const override
nPorts
Returns the number of ports the node has per type of port.
Parameters
QtNodes::PortType port_type : The type of port to get the number of ports. QtNodes::PortType::In (input), QtNodes::PortType::Out (output)
Returns
unsigned int : The number of ports.
outData()
std::shared_ptr< QtNodes::NodeData > ConverterClampNode::outData (QtNodes::PortIndex port)
outData
Returns a shared pointer for transport along a connection to another node.
Parameters
QtNodes::PortIndex port : The port to get data from.
Returns
std::shared_ptr<QtNodes::NodeData> : The shared output data.
restore()
void ConverterClampNode::restore (QJsonObject const & data) override
restore
Restores the state of the node from a provided json object.
Parameters
QJsonObject const& data : The data to restore from.
save()
QJsonObject ConverterClampNode::save () const override
save
Saves the state of the node into a QJsonObject for the system to save to file.
Returns
QJsonObject : The saved state of the node.
setInData()
void ConverterClampNode::setInData (std::shared_ptr< QtNodes::NodeData > node_data, QtNodes::PortIndex port)
setInData
Sets the input data on a port.
Parameters
std::shared_ptr<QtNodes::NodeData> node_data : The shared pointer data being inputted.
QtNodes::PortIndex port : The port the data is being set on.
sharedWidget()
QWidget * ConverterClampNode::sharedWidget () virtual
sharedWidget
Returns a pointer to the widget that gets displayed in the properties panel.
Returns
QWidget* : The shared widget.
Reimplemented from Node.
sigmoid()
double ConverterClampNode::sigmoid (double v, double min, double max) static
sigmoid
Algorithm to truncate values beyond the min and max value using the sigmoid algorithm to smoothly clamp the values between the min and max value.
Parameters
double v : The value to be truncated.
double min : The minimum value.
double max : The maximum value.
Returns
double : The truncated value.
Referenced by _generate().
The documentation for this class was generated from the following files:
src/Nodeeditor/Nodes/clamp.h
src/Nodeeditor/Nodes/clamp.cpp