Terrain Generator: NormalMapGenerator Class Reference
NormalMapGenerator Class Reference
#include <normal.h>
Public Slots
void normalDone (QImage const &normal_map)
Signals
void done ()
void progress (int perc)
void started ()
Public Member Functions
NormalMapGenerator ()
~NormalMapGenerator ()
NormalMapGenerator (IntensityMap height_map)
void generate ()
void setImage (IntensityMap height_map)
QImage toImage ()
Private Attributes
int _width
int _height
int _gen_size
QThread _normal_thread
NormalWorker * _worker = nullptr
QImage _normal_map
IntensityMap _height_map
Detailed Description
NormalMapGenerator
Class that is used to generate the normal map.
Constructor & Destructor Documentation
NormalMapGenerator() [1/2]
NormalMapGenerator::NormalMapGenerator ()
NormalMapGenerator
Creates a normal map generator
~NormalMapGenerator()
NormalMapGenerator::~NormalMapGenerator ()
~NormalMapGenerator
Deletes the simplex noise, safely shutting down the worker thread.
NormalMapGenerator() [2/2]
NormalMapGenerator::NormalMapGenerator (IntensityMap height_map)
NormalMagGenerator
Create a new normal map generator with a pre set height map.
Member Function Documentation
generate()
void NormalMapGenerator::generate ()
generate
Generates the normal map.
Referenced by OutputNode::_generateNormalMap().
normalDone
void NormalMapGenerator::normalDone (QImage const & normal_map) slot
normalDone
Called when the generation by the worker object has completed the normal map.
Parameters
QImage const& normal_map : The generated normal map.
done
Referenced by generate().
setImage()
void NormalMapGenerator::setImage (IntensityMap height_map)
setImage
Sets the intensity map to be used to calculate the normal map from.
Parameters
IntensityMap height_map : The updated height map.
Referenced by OutputNode::_generateNormalMap().
toImage()
QImage NormalMapGenerator::toImage ()
toImage
Returns the normal map.
Returns
QImage : The generated normal map.
Referenced by OutputNode::OutputNode().
The documentation for this class was generated from the following files:
src/Nodeeditor/Nodes/Normal/normal.h
src/Nodeeditor/Nodes/Normal/normal.cpp