Terrain Generator: Texture Class Reference
Texture Class Reference
#include <texturelist.h>
Signals
void updated ()
Public Member Functions
Texture ()
Texture (QString filename)
Texture (QByteArray data, QString filename)
Texture (int w, int h)
Texture (int w, int h, QString filename)
QPixmap pixmap (int scale=-1)
QImage image (int scale=-1)
QIcon icon ()
bool bytes (QByteArray *bytes)
bool generated ()
bool edited ()
QString name ()
QString filename ()
QString saveName ()
VectorMap vectorMap (int scale=-1)
void replace (QPixmap pixmap)
IntensityMap intensityMap (IntensityMap::Channel channel, int scale=-1)
void draw (Stencil *stencil, QPointF pos)
bool save ()
bool save (QIODevice *device)
bool saveAs (QString filename)
Private Attributes
QString _filename = ""
QPixmap _pixmap
QPainter * _painter
bool _generated = false
bool _edited = false
Detailed Description
Texture
The texture class houses loaded and generated textures that are provided in the InputTextureNode class and edited with the drawing singleton.
Constructor & Destructor Documentation
Texture() [1/5]
Texture::Texture ()
Texture
Plain constructor for complete new texture. (not used, may remove)
Referenced by TextureList::addTexture(), and TextureList::loadTexture().
Texture() [2/5]
Texture::Texture (QString filename)
Texture
Constructs a texture from the given filename.
Parameters
QString filename : The file to create the texture from.
Texture() [3/5]
Texture::Texture (QByteArray data, QString filename)
Texture
Create a texture from a raw byte array, used for loading the texture directly from the save zip file that is loaded with Quazip.
Parameters
QByteArray data : The raw data of the texture.
QString filename : The filename of the texture.
Texture() [4/5]
Texture::Texture (int w, int h)
Texture
Creates a new empty texture (for drawing on) with only the width and height set.
Parameters
int w : The width of the new texture.
int h : The height of the new texture.
Texture() [5/5]
Texture::Texture (int w, int h, QString filename)
Texture
Creates a new empty texture (for drawing on) with the width, height, and filename set.
Parameters
int w : The width of the new texture.
int h : The height of the new texture.
QString filename : The filname of the texture (Texture_#).
Member Function Documentation
bytes()
bool Texture::bytes (QByteArray * bytes)
bytes
Saves the texture to the provided byte array pointer. This saves the raw data of the image to the byte array (used for saving to zip file). Saves generated textures using the png format. Loaded files use the file format.
Parameters
QByteArray* bytes : The pointer to the bytearray to save the data to.
Returns
bool : Wether or not the operation was successful.
draw()
void Texture::draw (Stencil * stencil, QPointF pos)
draw
Draw the stencil onto the stencil directly.
Parameters
Stencil* stencil : The stencil to draw with.
QPointF pos : The position that the stencil should draw to.
updated
edited()
bool Texture::edited ()
edited
Returns whether or not the texture was edited or not.
Returns
bool : Whether or not the texture is edited.
filename()
QString Texture::filename ()
filename
The name of the texture (filename). "/path/to/myfile.png" -> "/path/to/myfile.png"
Returns
QString : The full filename of the file.
Referenced by TextureList::addTexture(), TextureList::find(), TextureList::loadTexture(), InputTextureNode::save(), and Texture().
generated()
bool Texture::generated ()
generated
Returns whether or not the texture was generated or not.
Returns
bool : Whether or not the texture is generated.
Referenced by MainWindow::_saveAsAccept(), bytes(), and InputTextureNode::save().
icon()
QIcon Texture::icon ()
icon
Returns the icon object of the texture.
Returns
QIcon : The icon of the texture.
image()
QImage Texture::image (int scale = -1)
image
Returns the QImage of the texture file. Uses pixmap above for returning the image.
Parameters
int scale : The scale of the image.
Returns
QImage : The image of the texture.
Referenced by Texture().
intensityMap()
IntensityMap Texture::intensityMap (IntensityMap::Channel channel, int scale = -1)
intensityMap
Returns the intensity map (a mono color vector map).
Parameters
IntensityMap::Channel channel : The channel to use for combining the pixel colours into a mono channel.
int scale : The scale of the output intensity map.
name()
QString Texture::name ()
name
The name of the texture (filename). "/path/to/myfile.png" -> "myfile.png".
Returns
QString : The name of the file.
Referenced by TextureList::find(), saveName(), and DrawingDialogue::show().
pixmap()
QPixmap Texture::pixmap (int scale = -1)
pixmap
Returns the QPixmap of the texture file.
Parameters
int scale : The scale that the pixmap should be done to, if the value is less than or 0 then no scale is applied.
Returns
QPixmap : The pixmap that is used.
Referenced by InputTextureNode::_setPixmaps(), image(), intensityMap(), DrawingDialogue::show(), DrawingDialogue::textureUpdated(), and vectorMap().
replace()
void Texture::replace (QPixmap pixmap)
replace
Used by the drawing system, this replaces the texture with the provided pixmap, this replacement is the saved drawn version of the texture. Currently there is no way to undo this process.
Parameters
QPixmap pixmap : The new pixmap that replaces the internal one.
updated
Todo:
Add a history option to allow for this operation to be undone. This can be done by using temp files.
save() [1/2]
bool Texture::save ()
save
Save the texture to an existing file.
Returns
bool : Whether or not the save was successful.
Todo:
Add option that if the texture is generated we first let the user select an output file.
Referenced by MainWindow::_saveAsAccept().
save() [2/2]
bool Texture::save (QIODevice * device)
save
Saves the file to the device provided (saves directly).
Parameters
QIODevice* device : Pointer to the device to save to directly.
saveAs()
bool Texture::saveAs (QString filename)
saveAs
Saves the texture to a specific location on the file using the filename.
Parameters
QString filename : The file to save to.
Returns
bool : Whether or not the operation was successful.
Referenced by save().
saveName()
QString Texture::saveName ()
saveName
The name of the texture (filename). "/path/to/myfile.png" -> "myfile.png" "Texture_#" -> "Texture_#.png"
Returns
QString : The save name of the file.
Referenced by MainWindow::_saveAsAccept(), and InputTextureNode::save().
vectorMap()
VectorMap Texture::vectorMap (int scale = -1)
vectorMap
Returns a vector map, which uses higher detail values of the texture.
Parameters
int scale : The scale of the output vector map.
Returns
VectorMap : The vector map of the texture.
Referenced by InputTextureNode::outData().
The documentation for this class was generated from the following files:
src/Globals/texturelist.h
src/Globals/texturelist.cpp