Terrain Generator: IntensityMap Class Reference
IntensityMap Class Reference
#include <intensitymap.h>
Public Types
enum Channel {
RED, GREEN, BLUE, ALPHA,
AVERAGE, MIN, MAX
}
Public Member Functions
IntensityMap ()
IntensityMap (int width, int height)
IntensityMap (int width, int height, double fill)
IntensityMap (int width, int height, std::vector< double > values)
IntensityMap (QImage image, IntensityMap::Channel channel)
IntensityMap (QPixmap image, IntensityMap::Channel channel)
QImage toImage (bool print_qimage=true)
QPixmap toPixmap ()
IntensityMap scaled (int width, int height)
IntensityMap transform (double func(double, double), double value)
IntensityMap transform (double func(double, double), IntensityMap *map)
double at (int x, int y, bool clamp_to=false)
bool usingFill ()
bool append (double value)
bool set (int x, int y, double value)
Public Attributes
int width
int height
std::vector< double > values
Private Member Functions
void _saveImage (QImage image, IntensityMap::Channel channel)
Private Attributes
double _fill = 0.00
bool _use_fill = false
Detailed Description
IntensityMap
Houses a 2 dimensional array (internally stored in 1 dimension) a list of doubles that create a mono-coloured image or height map.
Constructor & Destructor Documentation
IntensityMap() [1/6]
IntensityMap::IntensityMap ()
IntensityMap
Creates a new empty map.
Referenced by scaled(), and transform().
IntensityMap() [2/6]
IntensityMap::IntensityMap (int width, int height)
IntensityMap
Create a new intensity map with a fixed size. The fill value inherits the default value. Fill is used instead of an array of values if the entire map is the same "colour."
Parameters
int width : The width of the map;
int height : The height of the map;
IntensityMap() [3/6]
IntensityMap::IntensityMap (int width, int height, double fill)
IntensityMap
Create a new intensity map with a fixed size and a specific fill value.
Parameters
int width : The width of the map.
int height : The height of the map.
double fill : The fill value of the entire map.
IntensityMap() [4/6]
IntensityMap::IntensityMap (int width, int height, std::vector< double > values)
IntensityMap
Create a new intensity map with a set size and with the mapped fill values for each pixel being set.
Parameters
int width : The width of the map.
int height : The height of the map.
std::vector<double> values : Each individual pixel value.
IntensityMap() [5/6]
IntensityMap::IntensityMap (QImage image, IntensityMap::Channel channel)
IntensityMap
Create the intensity map from a supplied image. The channel selected determines how to select the value for the intensity for each pixel.
Parameters
QImage image : The input image to create map from.
IntensityMap::Channel channel : The channel to select value. RED, GREEN, BLUE, ALPHA, AVERAGE ((r + b + g + a) / 4), MIN (smallest channel), MAX (largest)
IntensityMap() [6/6]
IntensityMap::IntensityMap (QPixmap image, IntensityMap::Channel channel)
IntensityMap
Create the intensity map from a supplied pixmap. See IntensityMap above for image to see how this works the same.
Parameters
QPixmap pixmap : The input puxmap to create map from.
IntensityMap::Channel channel : The channel to select pixel value.
Member Function Documentation
_saveImage()
void IntensityMap::_saveImage (QImage image, IntensityMap::Channel channel) private
_saveImage
Helper function used to convert a supplied QImage (or QPixmap that is casted into a QImage) into an intensity map.
Parameters
QImage image : The image used to pull information from.
IntensityMap::Channel channel : The channel to create the map from.
Referenced by IntensityMap().
append()
bool IntensityMap::append (double value)
append
Appends a value to the end of the values list of intensities.
Parameters
double value : The value to be appended.
Returns
bool : Whether the value was appended or not.
Referenced by ConverterInvertIntensityNode::_generate(), ConverterColorSplitNode::_generate(), ConverterSmoothNode::_generate(), ConverterBezierCurveNode::_generate(), ConverterClampNode::_generate(), ConverterVectorDotNode::_generate(), SimplexNoiseWorker::generate(), VectorMap::toIntensityMap(), and transform().
at()
double IntensityMap::at (int x, int y, bool clamp_to = false)
at
Get the value at a specific index of the map. If the requested index is beyond the bounds of the map the fill value is returned instead.
Parameters
int x : The column.
int y : The row.
bool clamp : Use the clamp value rather than the fill, default=false;
Returns
double : The intensity at the specified index.
Referenced by ConverterInvertIntensityNode::_generate(), ConverterSmoothNode::_generate(), ConverterBezierCurveNode::_generate(), ConverterColorCombineNode::_generate(), ConverterClampNode::_generate(), NormalWorker::_getHeightIntensity(), ConverterErosionNode::_smooth(), VectorMap::fromIntensityMap(), toImage(), and transform().
scaled()
IntensityMap IntensityMap::scaled (int width, int height)
scaled
Scales the intensity map into a new value. This uses a QImage under the hood to take advantage of Qt image scaling with linear interpolation.
Parameters
int width : The new width to scale to.
int height : The new height to scale to.
Returns
IntensityMap : The new updated intensity map.
set()
bool IntensityMap::set (int x, int y, double value)
set
Overrides a specific intensity value at a the specififed index.
Parameters
int x : The column.
int y : The row.
double value : The value to be overriding with.
Returns
bool : Wether the value was overridden or not.
Referenced by ConverterErosionNode::_smooth().
toImage()
QImage IntensityMap::toImage (bool print_qimage = true)
toImage
Returns the intensity map as an image with the value copied across all channels.
Parameters
bool print_qimage : Debugging option, the user should not use this.
Returns
QImage : The image.
Referenced by scaled(), and toPixmap().
toPixmap()
QPixmap IntensityMap::toPixmap ()
toPixmap
Returns the intensity as a pixmap for display.
Returns
QPixmap : The pixmap.
transform() [1/2]
IntensityMap IntensityMap::transform (double funcdouble, double, double value)
transform
Returns a new intensity map using a tranformation function with a fixed value by applying the function with the value to each pixel.
Parameters
[](double,double){} -> double : The function that applies the transformation.
double value : The fixed value used in the function.
Returns
IntensityMap : The new transformed intensity map.
Referenced by ConverterMathNode::_generate().
transform() [2/2]
IntensityMap IntensityMap::transform (double funcdouble, double, IntensityMap * map)
transform
Tranform the intensity map pixel by pixel by appling the provided function with another intensity map.
Parameters
[](double,double){} -> double : The transformation function.
IntensityMap* map : The other map to apply the transformation with.
Returns
IntensityMap : The newly transformed function.
usingFill()
bool IntensityMap::usingFill ()
usingFill
Returns true if the intensity map is using the fill value. i.e. no pixel manipulation has occured, it is a solid value map.
Returns
bool : Whether or not the map is only using fill.
Referenced by ConverterBezierCurveNode::_generate(), toImage(), and transform().
The documentation for this class was generated from the following files:
src/Nodeeditor/Datatypes/intensitymap.h
src/Nodeeditor/Datatypes/intensitymap.cpp