Terrain Generator: ConverterVectorIntensityNode Class Reference
ConverterVectorIntensityNode Class Reference
#include <vectorintensity.h>
Public Slots
void inputConnectionDeleted (QtNodes::Connection const &connection)
void modeChanged (int index)
Public Member Functions
ConverterVectorIntensityNode ()
void created () override
QString caption () const override
QString name () const override
QWidget * embeddedWidget ()
QWidget * sharedWidget ()
unsigned int nPorts (QtNodes::PortType port_type) const override
QtNodes::NodeDataType dataType (QtNodes::PortType port_type, QtNodes::PortIndex port_index) const override
std::shared_ptr< QtNodes::NodeData > outData (QtNodes::PortIndex port)
QJsonObject save () const override
void restore (QJsonObject const &data) override
void setInData (std::shared_ptr< QtNodes::NodeData > node_data, QtNodes::PortIndex port_index)
virtual bool hasShared ()
Private Member Functions
void _generate ()
Private Attributes
std::shared_ptr< VectorMapData > _input
bool _set = false
IntensityMap::Channel _channel = IntensityMap::AVERAGE
IntensityMap _output {1, 1, 1.00}
Ui::VectorIntensityNode _ui
Ui::VectorIntensityNode _shared_ui
QWidget * _widget
QWidget * _shared_widget
Detailed Description
ConverterVectorIntensityNode
Node to let users select a specific method from IntensityMap mode to convert a vector map to an intensity map.
Constructor & Destructor Documentation
ConverterVectorIntensityNode()
ConverterVectorIntensityNode::ConverterVectorIntensityNode ()
ConverterVectorIntensityNode
Creates the node and the UI.
Member Function Documentation
_generate()
void ConverterVectorIntensityNode::_generate () private
_generate
Generates the output data from the supplied and available data.
dataUpdated
Referenced by inputConnectionDeleted(), modeChanged(), and setInData().
caption()
QString ConverterVectorIntensityNode::caption () const override
caption
Return a string that is displayed on the node and in the properties.
Returns
QString : The caption.
created()
void ConverterVectorIntensityNode::created () override virtual
created
Function is called when the node is created so it can connect to listeners.
dataUpdated
Reimplemented from Node.
dataType()
QtNodes::NodeDataType ConverterVectorIntensityNode::dataType (QtNodes::PortType port_type, QtNodes::PortIndex port_index) const override
dataType
Returns the data type for each of the ports.
Parameters
QtNodes::PortType port_type : The type of port (in or out).
QtNodes::PortIndex port_index : The port index on each side.
Returns
QtNodes::NodeDataType : The type of data the port provides/accepts.
embeddedWidget()
QWidget * ConverterVectorIntensityNode::embeddedWidget ()
embeddedWidget
Returns a pointer to the widget that gets embedded within the node in the dataflow diagram.
Returns
QWidget* : The embedded widget.
inputConnectionDeleted
void ConverterVectorIntensityNode::inputConnectionDeleted (QtNodes::Connection const & connection) slot
inputConnectionDeleted
Called when an input connection is deleted, this usually resets some data and regenerates the output data.
Parameters
QtNodes::Connection const& connection : The connection being deleted.
modeChanged
void ConverterVectorIntensityNode::modeChanged (int index) slot
modeChanged
Called to change the mode used to convert the vector map. Regenerates the output.
Parameters
int index : The new mode.
Referenced by created().
name()
QString ConverterVectorIntensityNode::name () const override
name
Return a string that is displayed in the node selection list.
Returns
QString : The name.
Referenced by save().
nPorts()
unsigned int ConverterVectorIntensityNode::nPorts (QtNodes::PortType port_type) const override
nPorts
Returns the number of ports the node has per type of port.
Parameters
QtNodes::PortType port_type : The type of port to get the number of ports. QtNodes::PortType::In (input), QtNodes::PortType::Out (output)
Returns
unsigned int : The number of ports.
outData()
std::shared_ptr< QtNodes::NodeData > ConverterVectorIntensityNode::outData (QtNodes::PortIndex port)
outData
Returns a shared pointer for transport along a connection to another node.
Parameters
QtNodes::PortIndex port : The port to get data from.
Returns
std::shared_ptr<QtNodes::NodeData> : The shared output data.
restore()
void ConverterVectorIntensityNode::restore (QJsonObject const & data) override
restore
Restores the state of the node from a provided json object.
Parameters
QJsonObject const& data : The data to restore from.
save()
QJsonObject ConverterVectorIntensityNode::save () const override
save
Saves the state of the node into a QJsonObject for the system to save to file.
Returns
QJsonObject : The saved state of the node.
setInData()
void ConverterVectorIntensityNode::setInData (std::shared_ptr< QtNodes::NodeData > node_data, QtNodes::PortIndex port_index)
setInData
Sets the input data on a port.
Parameters
std::shared_ptr<QtNodes::NodeData> node_data : The shared pointer data being inputted.
QtNodes::PortIndex port : The port the data is being set on.
sharedWidget()
QWidget * ConverterVectorIntensityNode::sharedWidget () virtual
sharedWidget
Returns a pointer to the widget that gets displayed in the properties panel.
Returns
QWidget* : The shared widget.
Reimplemented from Node.
The documentation for this class was generated from the following files:
src/Nodeeditor/Nodes/vectorintensity.h
src/Nodeeditor/Nodes/vectorintensity.cpp