Terrain Generator: DrawingDialogue Class Reference
DrawingDialogue Class Reference
#include <drawing.h>
Public Slots
void textureUpdated ()
void newTexture (int index)
void undo ()
Public Member Functions
~DrawingDialogue ()
void show ()
void show (int index)
Static Public Member Functions
static DrawingDialogue * getInstance ()
Protected Member Functions
bool eventFilter (QObject *object, QEvent *event)
Private Member Functions
DrawingDialogue ()
Private Attributes
double _brush = 8.00
double _opacity = 100.00
double _flow_rate = 99.00
QColor _color {0, 0, 0, 255}
Stencil * _active_stencil = nullptr
int _active_stencil_button = 0
std::vector< QPushButton * > _stencil_buttons
bool _applied = true
Texture * _original_texture = nullptr
QPixmap _combined_pixmap
QPixmap _applied_pixmap
QPixmap _drawing_pixmap
std::vector< QPixmap > _history
QPainter * _applied_painter = nullptr
QPainter * _drawing_painter = nullptr
QDialog _dialogue
Ui::TextureDrawingDialogue _ui
QGraphicsScene * _scene
QGraphicsPixmapItem * _pixmap
QGraphicsEllipseItem * _brush_indicator
QPointF _prev
QStandardItemModel _texture_list_model
QModelIndex _selected_model
Static Private Attributes
static bool _instance = false
static DrawingDialogue * _single = nullptr
Detailed Description
DrawingDialogue
This is a singleton class that houses a drawing dialogue. Within the dialogue the user can select existing textures and draw on them to create new textures.
Constructor & Destructor Documentation
~DrawingDialogue()
DrawingDialogue::~DrawingDialogue ()
~DrawingDialogue
Deletes the singleton, removing reference to being instantiated.
DrawingDialogue()
DrawingDialogue::DrawingDialogue () private
DrawingDialogue
Creates the drawing interface singleton. Gets a list of stencils and places them into the stencil selection list. Gets a list of textures already loaded and places them into a visual texture list.
Todo:
include overlay of heightmap on OpenGL terrain.
Referenced by getInstance().
Member Function Documentation
eventFilter()
bool DrawingDialogue::eventFilter (QObject * object, QEvent * event) protected
eventFilter
Filters events that are done to the viewport, this is used for drawing onto the image canvas.
Parameters
QObject* object : Must be set for the eventFilter by Qt standards. However the parameter is not used.
QEvent* event : The event that was done, depending on if the event was a mouse press/release/move/wheel or key press different actions are taken.
getInstance()
DrawingDialogue * DrawingDialogue::getInstance () static
getInstance
Returns a pointer reference to the DrawingDialogue singleton. If the singleton does not exist yet the singleton is created before being shared.
Returns
DrawingDialogue* : Returns a pointer to the singleton.
newTexture
void DrawingDialogue::newTexture (int index) slot
newTexture
When the TextureList (TEXTURES) has created a new texture we listen for a signal and update the texture list displayed in the ui.
Parameters
int index : The new texture index in the TextureList.
show() [1/2]
void DrawingDialogue::show ()
show
Shows the drawing dialogue.
show() [2/2]
void DrawingDialogue::show (int index)
Show
Shows the dialogue selecting a specific texture to be edited/displayed.
Parameters
int index : The index of the texture to display for editing/viewing.
textureUpdated
void DrawingDialogue::textureUpdated () slot
textureUpdated
Function is called when the user draws on the surface, this merges the texture layer, the current drawing layer, and the history stack into a single pixmap that displays the resulting drawn texture.
Referenced by eventFilter(), show(), and undo().
undo
void DrawingDialogue::undo () slot
undo
When called the top most action (latest drawing action) is removed from the history stack. No redo is supported yet.
Todo:
Implement redo functionality.
Referenced by eventFilter().
The documentation for this class was generated from the following files:
src/Globals/drawing.h
src/Globals/drawing.cpp