Terrain Generator: IntensityMapData Class Reference
IntensityMapData Class Reference
#include <pixmap.h>
Public Member Functions
IntensityMapData ()
IntensityMapData (IntensityMap const &intensity_map)
QtNodes::NodeDataType type () const override
IntensityMap intensityMap () const
Private Attributes
IntensityMap _intensity_map
Detailed Description
IntensityMapData
Class that wraps an intensity map for transport between nodes in a connection
Constructor & Destructor Documentation
IntensityMapData() [1/2]
IntensityMapData::IntensityMapData ()
IntensityMapData
Creates a new intensity map data.
IntensityMapData() [2/2]
IntensityMapData::IntensityMapData (IntensityMap const & intensity_map)
IntensityMapData
Creates a new intensity map data using the provided intensity map.
Parameters
IntenistyMap const& intensity_map : The housed intensity map.
Member Function Documentation
intensityMap()
IntensityMap IntensityMapData::intensityMap () const
intensityMap
Returns the housed intensity map.
Returns
IntensityMap : The intensity map.
type()
QtNodes::NodeDataType IntensityMapData::type () const override
type
Returns the type that the container is. This is used to determine what ports can accept this data and the label on those ports.
Returns
QtNodes::NodeDataType : The type of data this is.
Referenced by ConverterInvertIntensityNode::dataType(), ConverterColorSplitNode::dataType(), OutputNode::dataType(), InputConstantValueNode::dataType(), ConverterSmoothNode::dataType(), ConverterVectorIntensityNode::dataType(), ConverterColorCombineNode::dataType(), ConverterVectorDotNode::dataType(), ConverterBezierCurveNode::dataType(), ConverterClampNode::dataType(), ConverterErosionNode::dataType(), ConverterMathNode::dataType(), and InputSimplexNoiseNode::dataType().
The documentation for this class was generated from the following files:
src/Nodeeditor/Datatypes/pixmap.h
src/Nodeeditor/Datatypes/pixmap.cpp