Terrain Generator: ConverterMathNode Class Reference
ConverterMathNode Class Reference
#include <math.h>
Public Types
enum Mode {
MIX, ADD, SUBTRACT, MULTIPLY,
DIVIDE, MIN, MAX, POW
}
Public Slots
void inputConnectionDeleted (QtNodes::Connection const &connection)
void val0Changed (double value)
void val1Changed (double value)
void comboChanged (int index)
Public Member Functions
ConverterMathNode ()
void created () override
QString caption () const override
QString name () const override
QWidget * embeddedWidget ()
QWidget * sharedWidget ()
unsigned int nPorts (QtNodes::PortType port_type) const override
QtNodes::NodeDataType dataType (QtNodes::PortType port_type, QtNodes::PortIndex port_index) const override
QJsonObject save () const override
void restore (QJsonObject const &data) override
std::shared_ptr< QtNodes::NodeData > outData (QtNodes::PortIndex port)
void setInData (std::shared_ptr< QtNodes::NodeData > node_data, QtNodes::PortIndex port)
virtual bool hasShared ()
Static Public Member Functions
static double mix (double a, double b)
static double add (double a, double b)
static double subtract (double a, double b)
static double multiply (double a, double b)
static double divide (double a, double b)
static double min (double a, double b)
static double max (double a, double b)
static double pow (double a, double b)
Private Member Functions
void _generate ()
Private Attributes
ConverterMathNode::Mode _mode = ConverterMathNode::MIX
IntensityMap _output {1, 1, 1.00}
std::shared_ptr< IntensityMapData > _in_0
std::shared_ptr< IntensityMapData > _in_1
double _val_in_0 = 1.00
double _val_in_1 = 1.00
bool _in_0_set = false
bool _in_1_set = false
Ui::MathNode _ui
Ui::MathNode _shared_ui
QWidget * _widget
QWidget * _shared_widget
Friends
class ConverterMathNode_Test
Detailed Description
ConverterMathNode
Node that takes in two intensity maps and applies a mathematical function to them. If either input is not set a default value is used instead.
Constructor & Destructor Documentation
ConverterMathNode()
ConverterMathNode::ConverterMathNode ()
ConverterMathNode
Creates the node and creates the UI.
Member Function Documentation
_generate()
void ConverterMathNode::_generate () private
_generate
Generates the output data from the supplied and available data.
dataUpdated
Referenced by comboChanged(), created(), inputConnectionDeleted(), setInData(), val0Changed(), and val1Changed().
add()
double ConverterMathNode::add (double a, double b) static
add
Adds the two values together.
Parameters
double a : The first value.
double b : The second value.
Returns
double : The resulting value.
Referenced by _generate().
caption()
QString ConverterMathNode::caption () const override
caption
Return a string that is displayed on the node and in the properties.
Returns
QString : The caption.
comboChanged
void ConverterMathNode::comboChanged (int index) slot
comboChanged
When the mode changes update the data and regenerate the output.
Parameters
int index : The mode to use.
Referenced by created().
created()
void ConverterMathNode::created () override virtual
created
Function is called when the node is created so it can connect to listeners.
Reimplemented from Node.
dataType()
QtNodes::NodeDataType ConverterMathNode::dataType (QtNodes::PortType port_type, QtNodes::PortIndex port_index) const override
dataType
Returns the data type for each of the ports.
Parameters
QtNodes::PortType port_type : The type of port (in or out).
QtNodes::PortIndex port_index : The port index on each side.
Returns
QtNodes::NodeDataType : The type of data the port provides/accepts.
divide()
double ConverterMathNode::divide (double a, double b) static
divide
Divides the two values together. If b is 0 (div by zero error) 0 is returned instead.
Parameters
double a : The first value.
double b : The second value.
Returns
double : The resulting value.
Referenced by _generate().
embeddedWidget()
QWidget * ConverterMathNode::embeddedWidget ()
embeddedWidget
Returns a pointer to the widget that gets embedded within the node in the dataflow diagram.
Returns
QWidget* : The embedded widget.
inputConnectionDeleted
void ConverterMathNode::inputConnectionDeleted (QtNodes::Connection const & connection) slot
inputConnectionDeleted
Called when an input connection is deleted, this usually resets some data and regenerates the output data.
Parameters
QtNodes::Connection const& connection : The connection being deleted.
max()
double ConverterMathNode::max (double a, double b) static
max
Returns the largest of the two values.
Parameters
double a : The first value.
double b : The second value.
Returns
double : The resulting value.
Referenced by _generate().
min()
double ConverterMathNode::min (double a, double b) static
min
Returns the smallest of the two values.
Parameters
double a : The first value.
double b : The second value.
Returns
double : The resulting value.
Referenced by _generate().
mix()
double ConverterMathNode::mix (double a, double b) static
mix
Averages the two values together.
Parameters
double a : The first value.
double b : The second value.
Returns
double : The resulting value.
Referenced by _generate().
multiply()
double ConverterMathNode::multiply (double a, double b) static
multiply
Multiplies the two values together.
Parameters
double a : The first value.
double b : The second value.
Returns
double : The resulting value.
Referenced by _generate().
name()
QString ConverterMathNode::name () const override
name
Return a string that is displayed in the node selection list.
Returns
QString : The name.
Referenced by save().
nPorts()
unsigned int ConverterMathNode::nPorts (QtNodes::PortType port_type) const override
nPorts
Returns the number of ports the node has per type of port.
Parameters
QtNodes::PortType port_type : The type of port to get the number of ports. QtNodes::PortType::In (input), QtNodes::PortType::Out (output)
Returns
unsigned int : The number of ports.
outData()
std::shared_ptr< QtNodes::NodeData > ConverterMathNode::outData (QtNodes::PortIndex port)
outData
Returns a shared pointer for transport along a connection to another node.
Parameters
QtNodes::PortIndex port : The port to get data from.
Returns
std::shared_ptr<QtNodes::NodeData> : The shared output data.
pow()
double ConverterMathNode::pow (double a, double b) static
pow
Raises a to the power of b.
Parameters
double a : The first value.
double b : The second value.
Returns
double : The resulting value.
Referenced by _generate().
restore()
void ConverterMathNode::restore (QJsonObject const & data) override
restore
Restores the state of the node from a provided json object.
Parameters
QJsonObject const& data : The data to restore from.
save()
QJsonObject ConverterMathNode::save () const override
save
Saves the state of the node into a QJsonObject for the system to save to file.
Returns
QJsonObject : The saved state of the node.
setInData()
void ConverterMathNode::setInData (std::shared_ptr< QtNodes::NodeData > node_data, QtNodes::PortIndex port)
setInData
Sets the input data on a port.
Parameters
std::shared_ptr<QtNodes::NodeData> node_data : The shared pointer data being inputted.
QtNodes::PortIndex port : The port the data is being set on.
sharedWidget()
QWidget * ConverterMathNode::sharedWidget () virtual
sharedWidget
Returns a pointer to the widget that gets displayed in the properties panel.
Returns
QWidget* : The shared widget.
Reimplemented from Node.
subtract()
double ConverterMathNode::subtract (double a, double b) static
subtract
Subtracts the two values together.
Parameters
double a : The first value.
double b : The second value.
Returns
double : The resulting value.
Referenced by _generate().
val0Changed
void ConverterMathNode::val0Changed (double value) slot
val0Changed
When the first override value changes update the data and regenerate the output.
Parameters
double value : The new value.
Referenced by created().
val1Changed
void ConverterMathNode::val1Changed (double value) slot
val1Changed
When the second override value changes update the data and regenerate the output.
Parameters
double value : The new value.
Referenced by created().
The documentation for this class was generated from the following files:
src/Nodeeditor/Nodes/math.h
src/Nodeeditor/Nodes/math.cpp