Terrain Generator: Stencil Class Reference
Stencil Class Reference
#include <stencillist.h>
Public Member Functions
Stencil (QString filename, int index)
Stencil (QString filename, double brush, int index)
Stencil (QString filename, double brush, QColor color, int index)
void setColor (QColor color)
void setAlpha (double value)
void setBrush (double brush)
void draw (QPainter *painter, QPointF pos)
int index ()
QString name ()
QIcon icon ()
Private Member Functions
void _generate ()
Private Attributes
int _index
QString _filename
double _brush = 8.00
QColor _color {0, 0, 0, 128}
IntensityMap _stencil
QPixmap _pixmap
QIcon _icon
Detailed Description
Stencil
A class that houses a stencil (image) that is used to draw specific shapes with alpha onto other pixmaps. Used within the drawing singleton.
Constructor & Destructor Documentation
Stencil() [1/3]
Stencil::Stencil (QString filename, int index)
Stencil
Create a new stencil from the provided file. Loads from texture. Sets the index that the stencil is within the stencillist.
Parameters
QString filename : The file to load the stencil texture from.
int index : The index that the stencil is in the stencillist.
Referenced by StencilList::StencilList().
Stencil() [2/3]
Stencil::Stencil (QString filename, double brush, int index)
Stencil
Create a new stencil from the provided file. Loads from texture. Sets the index that the stencil is within the stencillist. Sets the radius of the stencil.
Parameters
QString filename : The file to load the stencil texture from.
double brush : The diameter of the stencil.
int index : The index that the stencil exists in the stencillist.
Stencil() [3/3]
Stencil::Stencil (QString filename, double brush, QColor color, int index)
Stencil
Create a new stencil from the provided file. Loads from texture. Sets the index that the stencil is within the stencillist. Sets the radius of the stencil. Sets the colour of the stencil that should be used.
Parameters
QString filename : The file to load the stencil texture from.
double brush : The stencil diameter.
QColor color : The stencil colour.
int index : The index that the stencil exists in the stencillist.
Member Function Documentation
_generate()
void Stencil::_generate () private
_generate
Generates the stencil and saves it as a pixmap (takes the texture and converts the red channel into a mask for alpha that applies colour stamp).
Referenced by setAlpha(), setBrush(), setColor(), and Stencil().
draw()
void Stencil::draw (QPainter * painter, QPointF pos)
draw
Draws the stencil with the provided painter (draw on pixmap with painter) at a specific position.
Parameters
QPainter* painter : The painter that is to be used to draw with.
QPointF pos : The position to draw the stencil to.
Referenced by Texture::draw(), and DrawingDialogue::eventFilter().
icon()
QIcon Stencil::icon ()
icon
Returns the icon of the stencil, used for brush selection.
Returns
QIcon : The icon of the stencil.
index()
int Stencil::index ()
index
Return the index that this stencil is in the stencil list.
Returns
int : The index that the stencil is in the stencil list.
Referenced by Stencil(), and StencilList::stencil().
name()
QString Stencil::name ()
name
The name of the stencil. "my-stencil-brush.png" -> "my stencil brush".
Returns
QString : The name of the stencil as displayed in the UI.
Referenced by Stencil().
setAlpha()
void Stencil::setAlpha (double value)
setAlpha
Set the opacity of the drawing stencil.
Parameters
double value : The alpha value
setBrush()
void Stencil::setBrush (double brush)
setBrush
Sets the stencil drawing diameter.
Parameters
double brush : The diameter to be set.
setColor()
void Stencil::setColor (QColor color)
setColor
Updates the stencils drawing colour.
Parameters
QColor color : The new colour to be used by the stencil.
The documentation for this class was generated from the following files:
src/Globals/stencillist.h
src/Globals/stencillist.cpp