Terrain Generator: ConverterVectorMathNode Class Reference
ConverterVectorMathNode Class Reference
#include <vectormath.h>
Public Types
enum Mode {
MIX, ADD, SUBTRACT, MULTIPLY,
DIVIDE, CROSS
}
Public Slots
void inputConnectionDeleted (QtNodes::Connection const &connection)
void x0Changed (double value)
void y0Changed (double value)
void z0Changed (double value)
void w0Changed (double value)
void x1Changed (double value)
void y1Changed (double value)
void z1Changed (double value)
void w1Changed (double value)
void modeChanged (int index)
Public Member Functions
ConverterVectorMathNode ()
void created () override
QString caption () const override
QString name () const override
QWidget * embeddedWidget ()
QWidget * sharedWidget ()
unsigned int nPorts (QtNodes::PortType port_type) const override
QtNodes::NodeDataType dataType (QtNodes::PortType port_type, QtNodes::PortIndex port_index) const override
QJsonObject save () const override
void restore (QJsonObject const &data) override
std::shared_ptr< QtNodes::NodeData > outData (QtNodes::PortIndex port)
void setInData (std::shared_ptr< QtNodes::NodeData > node_data, QtNodes::PortIndex port)
virtual bool hasShared ()
Static Public Member Functions
static glm::dvec4 mix (glm::dvec4 a, glm::dvec4 b)
static glm::dvec4 add (glm::dvec4 a, glm::dvec4 b)
static glm::dvec4 subtract (glm::dvec4 a, glm::dvec4 b)
static glm::dvec4 multiply (glm::dvec4 a, glm::dvec4 b)
static glm::dvec4 divide (glm::dvec4 a, glm::dvec4 b)
static glm::dvec4 cross (glm::dvec4 a, glm::dvec4 b)
Private Member Functions
void _generate ()
Private Attributes
ConverterVectorMathNode::Mode _mode = ConverterVectorMathNode::MIX
VectorMap _output {1, 1, glm::dvec4{1.00, 1.00, 1.00, 1.00}}
std::shared_ptr< VectorMapData > _in_0
std::shared_ptr< VectorMapData > _in_1
glm::dvec4 _val_in_0 {1.00, 1.00, 1.00, 1.00}
glm::dvec4 _val_in_1 {1.00, 1.00, 1.00, 1.00}
bool _in_0_set = false
bool _in_1_set = false
Ui::VectorMathNode _ui
Ui::VectorMathNode _shared_ui
QWidget * _widget
QWidget * _shared_widget
Friends
class ConverterVectorMathNode_Test
Detailed Description
ConverterVectorMathNode
Node that applies different math operations on two vectors that produce a vector. (elementwise multiply or add)
Constructor & Destructor Documentation
ConverterVectorMathNode()
ConverterVectorMathNode::ConverterVectorMathNode ()
ConverterMathNode
Creates the node and the UI.
Member Function Documentation
_generate()
void ConverterVectorMathNode::_generate () private
_generate
Generates the output data from the supplied and available data.
dataUpdated
Referenced by created(), inputConnectionDeleted(), modeChanged(), restore(), setInData(), w0Changed(), w1Changed(), x0Changed(), x1Changed(), y0Changed(), y1Changed(), z0Changed(), and z1Changed().
add()
glm::dvec4 ConverterVectorMathNode::add (glm::dvec4 a, glm::dvec4 b) static
add
Adds the two vectors together.
Parameters
glm::dvec4 a : The first vector.
glm::dvec4 b : The second vector.
Returns
glm::dvec4 : The resulting vector.
Referenced by _generate().
caption()
QString ConverterVectorMathNode::caption () const override
caption
Return a string that is displayed on the node and in the properties.
Returns
QString : The caption.
created()
void ConverterVectorMathNode::created () override virtual
created
Function is called when the node is created so it can connect to listeners.
Reimplemented from Node.
cross()
glm::dvec4 ConverterVectorMathNode::cross (glm::dvec4 a, glm::dvec4 b) static
cross
Uses the cross product on the two vectors. (only considers the first 3 values as cross is only defined for 3 and 7 length vectors, w is replaced by 1.00).
Parameters
glm::dvec4 a : The first vector.
glm::dvec4 b : The second vector.
Returns
glm::dvec4 : The resulting vector.
Referenced by _generate().
dataType()
QtNodes::NodeDataType ConverterVectorMathNode::dataType (QtNodes::PortType port_type, QtNodes::PortIndex port_index) const override
dataType
Returns the data type for each of the ports.
Parameters
QtNodes::PortType port_type : The type of port (in or out).
QtNodes::PortIndex port_index : The port index on each side.
Returns
QtNodes::NodeDataType : The type of data the port provides/accepts.
divide()
glm::dvec4 ConverterVectorMathNode::divide (glm::dvec4 a, glm::dvec4 b) static
divide
Divides the two vectors together elementwise. If any b values are 0, 0 is uses rather than occuring a divide by zero error.
Parameters
glm::dvec4 a : The first vector.
glm::dvec4 b : The second vector.
Returns
glm::dvec4 : The resulting vector.
Referenced by _generate().
embeddedWidget()
QWidget * ConverterVectorMathNode::embeddedWidget ()
embeddedWidget
Returns a pointer to the widget that gets embedded within the node in the dataflow diagram.
Returns
QWidget* : The embedded widget.
inputConnectionDeleted
void ConverterVectorMathNode::inputConnectionDeleted (QtNodes::Connection const & connection) slot
inputConnectionDeleted
Called when an input connection is deleted, this usually resets some data and regenerates the output data.
Parameters
QtNodes::Connection const& connection : The connection being deleted.
mix()
glm::dvec4 ConverterVectorMathNode::mix (glm::dvec4 a, glm::dvec4 b) static
mix
Averages the two vectors together.
Parameters
glm::dvec4 a : The first vector.
glm::dvec4 b : The second vector.
Returns
glm::dvec4 : The resulting vector.
Referenced by _generate().
modeChanged
void ConverterVectorMathNode::modeChanged (int index) slot
modeChanged
Changes the mode that selects what algorithm to apply to the two vectors.
Parameters
int index : The new mode.
Referenced by created().
multiply()
glm::dvec4 ConverterVectorMathNode::multiply (glm::dvec4 a, glm::dvec4 b) static
multiply
Multiplies the two vectors together elementwise.
Parameters
glm::dvec4 a : The first vector.
glm::dvec4 b : The second vector.
Returns
glm::dvec4 : The resulting vector.
Referenced by _generate().
name()
QString ConverterVectorMathNode::name () const override
name
Return a string that is displayed in the node selection list.
Returns
QString : The name.
Referenced by save().
nPorts()
unsigned int ConverterVectorMathNode::nPorts (QtNodes::PortType port_type) const override
nPorts
Returns the number of ports the node has per type of port.
Parameters
QtNodes::PortType port_type : The type of port to get the number of ports. QtNodes::PortType::In (input), QtNodes::PortType::Out (output)
Returns
unsigned int : The number of ports.
outData()
std::shared_ptr< QtNodes::NodeData > ConverterVectorMathNode::outData (QtNodes::PortIndex port)
outData
Returns a shared pointer for transport along a connection to another node.
Parameters
QtNodes::PortIndex port : The port to get data from.
Returns
std::shared_ptr<QtNodes::NodeData> : The shared output data.
restore()
void ConverterVectorMathNode::restore (QJsonObject const & data) override
restore
Restores the state of the node from a provided json object.
Parameters
QJsonObject const& data : The data to restore from.
save()
QJsonObject ConverterVectorMathNode::save () const override
save
Saves the state of the node into a QJsonObject for the system to save to file.
Returns
QJsonObject : The saved state of the node.
setInData()
void ConverterVectorMathNode::setInData (std::shared_ptr< QtNodes::NodeData > node_data, QtNodes::PortIndex port)
setInData
Sets the input data on a port.
Parameters
std::shared_ptr<QtNodes::NodeData> node_data : The shared pointer data being inputted.
QtNodes::PortIndex port : The port the data is being set on.
sharedWidget()
QWidget * ConverterVectorMathNode::sharedWidget () virtual
sharedWidget
Returns a pointer to the widget that gets displayed in the properties panel.
Returns
QWidget* : The shared widget.
Reimplemented from Node.
subtract()
glm::dvec4 ConverterVectorMathNode::subtract (glm::dvec4 a, glm::dvec4 b) static
subtract
Subtracts the two vectors together.
Parameters
glm::dvec4 a : The first vector.
glm::dvec4 b : The second vector.
Returns
glm::dvec4 : The resulting vector.
Referenced by _generate().
w0Changed
void ConverterVectorMathNode::w0Changed (double value) slot
w0Changed
Changes the w value on the first vector.
Parameters
double value : The new value.
w1Changed
void ConverterVectorMathNode::w1Changed (double value) slot
w1Changed
Changes the w value on the second vector.
Parameters
double value : The new value.
x0Changed
void ConverterVectorMathNode::x0Changed (double value) slot
x0Changed
Changes the x value on the first vector.
Parameters
double value : The new value.
Referenced by created().
x1Changed
void ConverterVectorMathNode::x1Changed (double value) slot
x1Changed
Changes the x value on the second vector.
Parameters
double value : The new value.
Referenced by created().
y0Changed
void ConverterVectorMathNode::y0Changed (double value) slot
y0Changed
Changes the y value on the first vector.
Parameters
double value : The new value.
Referenced by created().
y1Changed
void ConverterVectorMathNode::y1Changed (double value) slot
y1Changed
Changes the y value on the second vector.
Parameters
double value : The new value.
Referenced by created().
z0Changed
void ConverterVectorMathNode::z0Changed (double value) slot
z0Changed
Changes the z value on the first vector.
Parameters
double value : The new value.
Referenced by created().
z1Changed
void ConverterVectorMathNode::z1Changed (double value) slot
z1Changed
Changes the z value on the second vector.
Parameters
double value : The new value.
Referenced by created().
The documentation for this class was generated from the following files:
src/Nodeeditor/Nodes/vectormath.h
src/Nodeeditor/Nodes/vectormath.cpp