Terrain Generator: OpenGL Class Reference
OpenGL Class Reference
#include <opengl.h>
Public Slots
void sunRotationX (int value)
void sunRotationY (int value)
void camRotationX (int value)
void camRotationY (int value)
void camZoom (int value)
void nodeeditorOutputUpdated (QImage normal_map, QImage height_map, QImage albedo_map)
Public Member Functions
OpenGL (QWidget *parent=0)
~OpenGL ()
void setTerrainDrawLines (bool lines)
void setTerrainColor (QColor color)
void setTerrainLineColor (QColor color)
void setTerrainMeshResolution (int resolution)
void setSkyColor (QColor color)
void setLightColor (QColor color)
bool terrainDrawLines ()
QColor terrainColor ()
QColor terrainLineColor ()
QColor skyColor ()
QColor lightColor ()
Protected Member Functions
void initializeGL () override
void resizeGL (int w, int h) override
void paintGL () override
void wheelEvent (QWheelEvent *event) override
void mousePressEvent (QMouseEvent *event) override
void mouseMoveEvent (QMouseEvent *event) override
Private Attributes
QVector3D _ambient {0.77, 0.84, 0.99}
Terrain * _terrain
Camera * _camera
Light * _light
QPoint _prev
QWidget * _controls
QSlider * _control_cam_zoom
QSlider * _control_cam_rotation_x
QDial * _control_cam_rotation_y
QSlider * _control_sun_rotation_x
QDial * _control_sun_rotation_y
Detailed Description
OpenGL
Custom OpenGL management widget over the QOpenGLWidget. Manages the terrain light and cameras. Displays the resulting widget
Constructor & Destructor Documentation
OpenGL()
OpenGL::OpenGL (QWidget * parent = 0) explicit
OpenGL
Create the opengl widget, setup the terrain, light, camera, and other information.
Parameters
QWidget* parent : Set the parent widget.
~OpenGL()
OpenGL::~OpenGL ()
~OpenGL
Deletes the pointers to the other values. Destroys the widget.
Member Function Documentation
camRotationX
void OpenGL::camRotationX (int value) slot
camRotationX
Update the camera rotation along the x-axis from the UI.
Parameters
int value : The new rotation value.
Referenced by OpenGL().
camRotationY
void OpenGL::camRotationY (int value) slot
camRotationY
Update the camera rotation along the y-axis from the UI.
Parameters
int value : The new rotation value.
Referenced by OpenGL().
camZoom
void OpenGL::camZoom (int value) slot
camZoom
Update the camera zoom value from UI.
Parameters
int value : The new zoom value.
Referenced by OpenGL().
initializeGL()
void OpenGL::initializeGL () override protected
initializeGL
Initializes the OpenGL functions, the parameters, the terrain, the camera, etc.
lightColor()
QColor OpenGL::lightColor ()
lightColor
Get the current sun colour.
Returns
QColor : The current light colour.
mouseMoveEvent()
void OpenGL::mouseMoveEvent (QMouseEvent * event) override protected
mouseMoveEvent
When the mouse is moved and the correct buttons are pressed we update the camera or the suns rotation as the mouse moves.
Parameters
QMouseEvent* event : The mouse move event.
mousePressEvent()
void OpenGL::mousePressEvent (QMouseEvent * event) override protected
mousePressEvent
On mouse press we save the previous position for relative mouse movement used for rotation in the move event.
Parameters
QMouseEvent* event : The mouse press event.
nodeeditorOutputUpdated
void OpenGL::nodeeditorOutputUpdated (QImage normal_map, QImage height_map, QImage albedo_map) slot
nodeeditorOutputUpdated
Called when the nodeeditor has updated normal/height maps from the dataflow diagram. Used to update the scene.
Parameters
QImage normal_map : The new normal map.
QImage height_map : The new height map.
QImage albedo_map : The new albedo map.
Referenced by MainWindow::setup().
paintGL()
void OpenGL::paintGL () override protected
paintGL
Updates the viewport, the gizmos, terrain, etc.
resizeGL()
void OpenGL::resizeGL (int w, int h) override protected
resizeGL
Updates the widget resolution, updates the gizmos, and updates the camera values.
Parameters
int w : The width of the widget.
iht h : The height of the widget.
setLightColor()
void OpenGL::setLightColor (QColor color)
setLightColor
Sets the colour of the sun.
Parameters
QColor color : The colour of the sun.
setSkyColor()
void OpenGL::setSkyColor (QColor color)
setSkyColor
Set the background colour of the sky, also used for the ambient colour.
Parameters
QColor color : The colour of the sky.
setTerrainColor()
void OpenGL::setTerrainColor (QColor color)
setTerrainColor
Sets the colour of the terrain.
Parameters
QColo color : The colour of the terrain.
setTerrainDrawLines()
void OpenGL::setTerrainDrawLines (bool lines)
setTerrainDrawLines
Set whether or not to draw terrain vertex lines.
Parameters
bool lines : Whether or not to draw the lines
setTerrainLineColor()
void OpenGL::setTerrainLineColor (QColor color)
setTerrainLineColor
Set the color of the terrain lines.
Parameters
QColor color : The colour of the terrain lines.
setTerrainMeshResolution()
void OpenGL::setTerrainMeshResolution (int resolution)
setTerrainMeshResolution
Sets the resolution of the terrain mesh.
Parameters
int resolution : The resolution of the mesh.
skyColor()
QColor OpenGL::skyColor ()
skyColor
Get the current sky colour.
Returns
QColor : The current sky colour.
sunRotationX
void OpenGL::sunRotationX (int value) slot
sunRotationX
Update the suns rotation along the x-axis from the UI.
Parameters
int value : The new rotation value.
Referenced by OpenGL().
sunRotationY
void OpenGL::sunRotationY (int value) slot
sunRotationY
Update the suns rotation along the y-axis from the UI.
Parameters
int value : The new rotation value.
Referenced by OpenGL().
terrainColor()
QColor OpenGL::terrainColor ()
terrainColor
Get the current terrain colour.
Returns
QColor : The current colour of the terrain.
terrainDrawLines()
bool OpenGL::terrainDrawLines ()
terrainDrawLines
Get whether we are drawing lines on the terrain or not.
Returns
bool : Whether the line are being drawn.
terrainLineColor()
QColor OpenGL::terrainLineColor ()
terrainLineColor
Get the colour of the terrain lines.
Returns
QColor : The current terrain line colour.
wheelEvent()
void OpenGL::wheelEvent (QWheelEvent * event) override protected
wheelEvent
When the wheel is scrolled we adjust the zoom value of the camera.
Parameters
QWheelEvent* event : The mouse scroll wheel event.
The documentation for this class was generated from the following files:
src/OpenGL/opengl.h
src/OpenGL/opengl.cpp