Terrain Generator: VectorMap Class Reference
VectorMap Class Reference
#include <vectormap.h>
Public Types
enum ColorMode {
APPLY, OVERRIDE_COLOR, OVERRIDE_MAP, MASK,
MASK_ALPHA
}
Public Member Functions
VectorMap ()
VectorMap (int width, int height)
VectorMap (int width, int height, glm::dvec4 fill)
VectorMap (int width, int height, std::vector< glm::dvec4 > values)
VectorMap (QImage image)
VectorMap (QPixmap image)
IntensityMap toIntensityMap (IntensityMap::Channel channel=IntensityMap::BLUE)
QImage toImage (bool print_qimage=true)
QPixmap toPixmap ()
VectorMap scaled (int width, int height)
bool usingFill ()
VectorMap transform (glm::dvec4 func(glm::dvec4, glm::dvec4), glm::dvec4 value)
VectorMap transform (glm::dvec4 func(glm::dvec4, glm::dvec4), VectorMap *map)
glm::dvec4 at (int x, int y)
bool append (glm::dvec4 value)
bool set (int x, int y, glm::dvec4 value)
Static Public Member Functions
static VectorMap fromIntensityMap (IntensityMap &map, glm::dvec4 color=glm::dvec4(1.00, 1.00, 1.00, 1.00), VectorMap::ColorMode mode=VectorMap::APPLY)
Public Attributes
int width
int height
std::vector< glm::dvec4 > values
Private Member Functions
void _saveImage (QImage image)
Private Attributes
glm::dvec4 _fill {0.00, 0.00, 0.00, 0.00}
bool _use_fill = false
Detailed Description
VectorMap
Houses a 2 dimensional array of (internally as a 1 dimensional array) of glm::dev4 (4 value double vector) a fourth dimension version of intensity map.
Constructor & Destructor Documentation
VectorMap() [1/6]
VectorMap::VectorMap ()
VectorMap
Create a new empty map.
Referenced by scaled(), and transform().
VectorMap() [2/6]
VectorMap::VectorMap (int width, int height)
VectorMap
Create a vector map with a set size and uses the default fill value.
Parameters
int width : The width of the map.
int height : The height of the map.
VectorMap() [3/6]
VectorMap::VectorMap (int width, int height, glm::dvec4 fill)
VectorMap
Create a vector map with a set size and provided fill value.
Parameters
int width : The width of the map.
int height : The height of the map.
glm::dvec4 fill : The fill value of the map.
VectorMap() [4/6]
VectorMap::VectorMap (int width, int height, std::vector< glm::dvec4 > values)
VectorMap
Create a vector map with a set size and a list of pixel values.
Parameters
int width : The width of the map.
int height : The height of the map.
std::vector<glm::dvec4> values : The pixel values of the map.
VectorMap() [5/6]
VectorMap::VectorMap (QImage image)
VectorMap
Create a vector map from a provided image.
Parameters
QImage image : The image to create the vector map from.
VectorMap() [6/6]
VectorMap::VectorMap (QPixmap image)
VectorMap
Create a vector map from a supplied pixmap.
Parameters
QPixmap pixmap : The provided pixmap.
Member Function Documentation
_saveImage()
void VectorMap::_saveImage (QImage image) private
_saveImage
Helper function used to convert QImage (or QPixmap converted to QImage) into a vector map, takes the rgba and converts the colour into a glm::dev4 for each pixel.
Parameters
QImage image : The image to convert to a vector map.
Referenced by VectorMap().
append()
bool VectorMap::append (glm::dvec4 value)
append
Appends values to the end of the value list.
Parameters
glm::dvec4 value : The value to append to the end of the list.
Returns
bool : Whether appending was successful or not.
Referenced by ConverterColorCombineNode::_generate(), fromIntensityMap(), and transform().
at()
glm::dvec4 VectorMap::at (int x, int y)
at
Get the specifc value at a supplied index. Returns the fill value if the index is beyond the bounds.
Parameters
int x : The column.
int y : The row.
Returns
glm::dvec4 : The value of the pixel index.
Referenced by ConverterColorSplitNode::_generate(), ConverterVectorDotNode::_generate(), toImage(), toIntensityMap(), and transform().
fromIntensityMap()
VectorMap VectorMap::fromIntensityMap (IntensityMap & map, glm::dvec4 color = glm::dvec4(1.00, 1.00, 1.00, 1.00), VectorMap::ColorMode mode = VectorMap::APPLY) static
fromIntensityMap
Create a vector map from an intensity map, using the selected color to be applied to the intensity map with the application colour mode.
Parameters
IntensityMap& map : The intensity map to create the vector map from.
glm::dvec4 color : The colour to be applied to the intensity map.
VectorMap::ColorMode : The colour mode to be used in applying the colour to the intensity map. APPLY (rgba * intensity), OVERRIDE_COLOR (rgb * intensity, a), OVERRIDE_MAP (rgb * intensity, intensity), MASK (rgb, intensity), MASK_ALPHA (rgb, a * intensity)
Returns
VectorMap : The created map from the supplied intensity map.
Referenced by Stencil::_generate(), IntensityToVectorMapConverter::operator()(), and Stencil::Stencil().
scaled()
VectorMap VectorMap::scaled (int width, int height)
scaled
Scaled the vector map to the specified size. Uses QImage under the hood to scale the vector map using Qt's linear interpolation.
Parameters
int width : The newly set width.
int height : The new set height.
Returns
VectorMap : The scaled vetor map.
set()
bool VectorMap::set (int x, int y, glm::dvec4 value)
set
Replace a value at a specified index with a specified value if the index is within accepted range.
Parameters
int x : The column.
int y : The row.
glm::dvec4 value : The value to replace with.
Returns
bool : Whether or not the value was applied.
toImage()
QImage VectorMap::toImage (bool print_qimage = true)
toImage
Converts the vector map to an image.
Parameters
bool print_qimage : Debug value whether to print converting or not.
Returns
QImage : The converted image.
Referenced by scaled(), and toPixmap().
toIntensityMap()
IntensityMap VectorMap::toIntensityMap (IntensityMap::Channel channel = IntensityMap::BLUE)
toIntensityMap
Convert the vector map to an intensity map.
Parameters
IntensityMap::Channel channel : The channel to select from.
Returns
IntensityMap : The newly created intensity map.
Referenced by ConverterVectorIntensityNode::_generate().
toPixmap()
QPixmap VectorMap::toPixmap ()
toPixmap
Convert the vector map to a pixmap.
Returns
QPixmap : The converted pixmap.
Referenced by Stencil::_generate().
transform() [1/2]
VectorMap VectorMap::transform (glm::dvec4 funcglm::dvec4, glm::dvec4, glm::dvec4 value)
transform
Transforms the vector map using the supplied function and a fixed value.
Parameters
[](glm::dvec4,glm::dvec4) -> glm::dvec4 {} : The transformation function.
glm::dvec4 value : The fixed value to be used in the transformation function.
Referenced by ConverterNormalizeNode::_generate(), and ConverterVectorMathNode::_generate().
transform() [2/2]
VectorMap VectorMap::transform (glm::dvec4 funcglm::dvec4, glm::dvec4, VectorMap * map)
transform
Transforms the vector map with s upplied function and another vector map.
Parameters
[](glm::dvec4,glm::dvec4) -> glm::dvec4 {} : The transformation function.
VectorMap* map : The other vector map to convert transforms this map with the function pixel by pixel.
usingFill()
bool VectorMap::usingFill ()
usingFill
Returns whether or not the vector map is entirely defiend by the fill value.
Returns
bool : Whether or not the fill value is used for the entire map.
Referenced by ConverterVectorDotNode::_generate(), and transform().
The documentation for this class was generated from the following files:
src/Nodeeditor/Datatypes/vectormap.h
src/Nodeeditor/Datatypes/vectormap.cpp