Terrain Generator: Nodeeditor Class Reference
Nodeeditor Class Reference
#include <nodeeditor.h>
Public Slots
void nodeCreated (QtNodes::Node &node)
void nodeDoubleClicked (QtNodes::Node &node)
void outputComputingFinished ()
void nodeDeleted (QtNodes::Node &node)
Signals
void outputUpdated (QImage normal_map, QImage height_map, QImage albedo_map)
Public Member Functions
Nodeeditor (QLayout *target, QWidget *properties)
~Nodeeditor ()
QImage getHeightMap ()
QImage getNormalMap ()
QImage getAlbedoMap ()
QJsonObject save ()
void load (QJsonObject data)
Private Member Functions
void _updatePropertieNodesShared (QWidget *shared)
void _updatePropertiesNode (QtNodes::NodeDataModel *node, bool swap=false)
Private Attributes
QtNodes::FlowScene * _scene = nullptr
QtNodes::FlowView * _view = nullptr
QWidget * _properties
QWidget * _properties_node = nullptr
OutputNode * _active_output = nullptr
Detailed Description
Nodeeditor
Class that wraps QtNodes flow view and flow scene (QGraphicsView/QGraphicsScene) and manages the nodes and signals.
Constructor & Destructor Documentation
Nodeeditor()
Nodeeditor::Nodeeditor (QLayout * target, QWidget * properties)
Nodeeditor
Creates a new nodeeditor with the target layout to place the flow view and the target widget for displaying properties.
Parameters
QLayout* target : The layout to place the flowview onto.
QWidget* properties : The widget to display sharedWidget on.
~Nodeeditor()
Nodeeditor::~Nodeeditor ()
~Nodeeditor
Delete the node editor and its managed QtNode items.
Member Function Documentation
_updatePropertieNodesShared()
void Nodeeditor::_updatePropertieNodesShared (QWidget * shared) private
_updatePropertiesNodesShared
Sets/replaces the properties dispayed in the side panel. If the pointer is null, it only removes and hides the properties panel.
Parameters
QWidget *shared : The widget to be displayed or nullptr to simply hide the panel.
Referenced by nodeDeleted().
_updatePropertiesNode()
void Nodeeditor::_updatePropertiesNode (QtNodes::NodeDataModel * node, bool swap = false) private
_updatePropertiesNode
Takes the input node data model and a flag and casts and gets the widget for displaying on the properties panel.
Parameters
QtNodes::NodeDataModel* node : Pointer to the node to get properties widget for.
bool swap : Whether we are swapping existing properties or creating a new one.
Todo:
Use new node.h method and remove CASTS
Referenced by nodeCreated(), and nodeDoubleClicked().
getAlbedoMap()
QImage Nodeeditor::getAlbedoMap ()
getAlbedoMap
Get the supplied albedo map, if the albedo map is not set we return a blank image.
Returns
QImage : The albedo map.
Referenced by outputComputingFinished().
getHeightMap()
QImage Nodeeditor::getHeightMap ()
getHeightMap
Get the generated height map, if the height map is not set we return a blank image.
Returns
QImage : The height map.
Referenced by outputComputingFinished().
getNormalMap()
QImage Nodeeditor::getNormalMap ()
getNormalMap
Get the generated normal map, if the normal map is not set we return a blank image.
Returns
QImage : The normal map.
Referenced by outputComputingFinished().
load()
void Nodeeditor::load (QJsonObject data)
load
Loads the dataflow diagram from a json object.
Parameters
QJsonObject data : The data to load from.
Referenced by MainWindow::load().
nodeCreated
void Nodeeditor::nodeCreated (QtNodes::Node & node) slot
nodeCreated
When a new node is created and placed into the scene. If the model is an output node we set the active output node and then we get any properties widget the node has.
Parameters
QtNodes::Node& node : The node that was created.
Referenced by Nodeeditor().
nodeDeleted
void Nodeeditor::nodeDeleted (QtNodes::Node & node) slot
nodeDeleted
When a node is deleted this slot updates the properties panel removing any current attached widget.
Parameters
QtNodes::Node& node : Not used in this function.
Referenced by Nodeeditor().
nodeDoubleClicked
void Nodeeditor::nodeDoubleClicked (QtNodes::Node & node) slot
nodeDoubleClicked
When a node is double clicked we set it as the active node (if output) and update the properties panel with the new nodes widget.
Parameters
QtNodes::Node& node : The node that was double clicked.
Referenced by Nodeeditor().
outputComputingFinished
void Nodeeditor::outputComputingFinished () slot
outputComputingFinished
When the output node has completed its computation (the sum of the dataflow) we emit changes to be displayed in the opengl widget.
outputUpdated
Referenced by nodeCreated(), and nodeDoubleClicked().
save()
QJsonObject Nodeeditor::save ()
save
Returns the QJsonObject version of the obtained raw byte data for the dataflow diagrams nodes. This is used to save to a project file.
Returns
QJsonObject : The combined node data.
Referenced by MainWindow::_saveAsAccept().
The documentation for this class was generated from the following files:
src/Nodeeditor/nodeeditor.h
src/Nodeeditor/nodeeditor.cpp