Terrain Generator: InputSimplexNoiseNode Class Reference
InputSimplexNoiseNode Class Reference
#include <inputsimplexnoise.h>
Public Slots
void inputConnectionDeleted (QtNodes::Connection const &connection)
void simplexDone ()
Public Member Functions
InputSimplexNoiseNode ()
~InputSimplexNoiseNode ()
void created () override
QString caption () const override
QString name () const override
QWidget * embeddedWidget ()
QWidget * sharedWidget ()
unsigned int nPorts (QtNodes::PortType port_type) const override
QtNodes::NodeDataType dataType (QtNodes::PortType port_type, QtNodes::PortIndex port_index) const override
std::shared_ptr< QtNodes::NodeData > outData (QtNodes::PortIndex port)
QJsonObject save () const override
void restore (QJsonObject const &data) override
void setInData (std::shared_ptr< QtNodes::NodeData > node_data, QtNodes::PortIndex port)
virtual bool hasShared ()
Private Slots
void octivesChanged (double value)
void frequencyChanged (double value)
void persistenceChanged (double value)
void xChanged (double value)
void yChanged (double value)
void zChanged (double value)
Private Member Functions
void _generate ()
Private Attributes
IntensityMap _intensity_map
QPixmap _output
SimplexNoise _noise
float _octives = 8.0f
float _frequency = 5.0f
float _persistence = 0.5f
QVector3D _offset {0.0f, 0.0f, 0.0f}
QThread _thread
SimplexNoiseWorker * _worker = nullptr
std::shared_ptr< IntensityMapData > _in_octives
std::shared_ptr< IntensityMapData > _in_frequency
std::shared_ptr< IntensityMapData > _in_persistence
std::shared_ptr< VectorMapData > _in_offset
bool _in_octives_set = false
bool _in_frequency_set = false
bool _in_persistence_set = false
bool _in_offset_set = false
QWidget * _widget
QWidget * _shared_widget
Ui::SimplexNoiseNode_no_scroll _ui
Ui::SimplexNoiseNode _shared_ui
Friends
class InputSimplexNoiseNode_Test
Detailed Description
InputSimplexNoiseNode
Input node for creating simplex noise textures.
Constructor & Destructor Documentation
InputSimplexNoiseNode()
InputSimplexNoiseNode::InputSimplexNoiseNode ()
InputSimplexNoiseNode
Creates the node and created the UI.
~InputSimplexNoiseNode()
InputSimplexNoiseNode::~InputSimplexNoiseNode ()
~InputSimplexNoiseNode
Deletes the simplex noise, safely shutting down the worker thread.
Member Function Documentation
_generate()
void InputSimplexNoiseNode::_generate () private
_generate
Generates the output data from the supplied and available data.
Referenced by created().
caption()
QString InputSimplexNoiseNode::caption () const override
caption
Return a string that is displayed on the node and in the properties.
Returns
QString : The caption.
created()
void InputSimplexNoiseNode::created () override virtual
created
Function is called when the node is created so it can connect to listeners.
Reimplemented from Node.
dataType()
QtNodes::NodeDataType InputSimplexNoiseNode::dataType (QtNodes::PortType port_type, QtNodes::PortIndex port_index) const override
dataType
Returns the data type for each of the ports.
Parameters
QtNodes::PortType port_type : The type of port (in or out).
QtNodes::PortIndex port_index : The port index on each side.
Returns
QtNodes::NodeDataType : The type of data the port provides/accepts.
embeddedWidget()
QWidget * InputSimplexNoiseNode::embeddedWidget ()
embeddedWidget
Returns a pointer to the widget that gets embedded within the node in the dataflow diagram.
Returns
QWidget* : The embedded widget.
frequencyChanged
void InputSimplexNoiseNode::frequencyChanged (double value) private slot
frequencyChanged
Called when the control widget changes the frequency. Updates values and regenerates the simplex noise.
Parameters
double value : The new value.
Referenced by created().
inputConnectionDeleted
void InputSimplexNoiseNode::inputConnectionDeleted (QtNodes::Connection const & connection) slot
inputConnectionDeleted
Called when an input connection is deleted, this usually resets some data and regenerates the output data.
Parameters
QtNodes::Connection const& connection : The connection being deleted.
name()
QString InputSimplexNoiseNode::name () const override
name
Return a string that is displayed in the node selection list.
Returns
QString : The name.
nPorts()
unsigned int InputSimplexNoiseNode::nPorts (QtNodes::PortType port_type) const override
nPorts
Returns the number of ports the node has per type of port.
Parameters
QtNodes::PortType port_type : The type of port to get the number of ports. QtNodes::PortType::In (input), QtNodes::PortType::Out (output)
Returns
unsigned int : The number of ports.
octivesChanged
void InputSimplexNoiseNode::octivesChanged (double value) private slot
octivesChanged
Called when the control widget changes the octives. Updates values and regenerates the simplex noise.
Parameters
double value : The new value.
Referenced by created().
outData()
std::shared_ptr< QtNodes::NodeData > InputSimplexNoiseNode::outData (QtNodes::PortIndex port)
outData
Returns a shared pointer for transport along a connection to another node.
Parameters
QtNodes::PortIndex port : The port to get data from.
Returns
std::shared_ptr<QtNodes::NodeData> : The shared output data.
persistenceChanged
void InputSimplexNoiseNode::persistenceChanged (double value) private slot
persistenceChanged
Called when the control widget changes the persistence. Updates values and regenerates the simplex noise.
Parameters
double value : The new value.
Referenced by created().
restore()
void InputSimplexNoiseNode::restore (QJsonObject const & data) override
restore
Restores the state of the node from a provided json object.
Parameters
QJsonObject const& data : The data to restore from.
save()
QJsonObject InputSimplexNoiseNode::save () const override
save
Saves the state of the node into a QJsonObject for the system to save to file.
Returns
QJsonObject : The saved state of the node.
setInData()
void InputSimplexNoiseNode::setInData (std::shared_ptr< QtNodes::NodeData > node_data, QtNodes::PortIndex port)
setInData
Sets the input data on a port.
Parameters
std::shared_ptr<QtNodes::NodeData> node_data : The shared pointer data being inputted.
QtNodes::PortIndex port : The port the data is being set on.
sharedWidget()
QWidget * InputSimplexNoiseNode::sharedWidget () virtual
sharedWidget
Returns a pointer to the widget that gets displayed in the properties panel.
Returns
QWidget* : The shared widget.
Reimplemented from Node.
simplexDone
void InputSimplexNoiseNode::simplexDone () slot
simplexDone
Called when the generation of the simplex noise in the other thread is done.
dataUpdated
Referenced by _generate().
xChanged
void InputSimplexNoiseNode::xChanged (double value) private slot
xChanged
Called when the control widget changes the x. Updates values and regenerates the simplex noise. updates the offset.
Parameters
double value : The new value.
Referenced by created().
yChanged
void InputSimplexNoiseNode::yChanged (double value) private slot
yChanged
Called when the control widget changes the y. Updates values and regenerates the simplex noise. updates the offset.
Parameters
double value : The new value.
Referenced by created().
zChanged
void InputSimplexNoiseNode::zChanged (double value) private slot
zChanged
Called when the control widget changes the z. Updates values and regenerates the simplex noise. updates the offset.
Parameters
double value : The new value.
Referenced by created().
The documentation for this class was generated from the following files:
src/Nodeeditor/Nodes/inputsimplexnoise.h
src/Nodeeditor/Nodes/inputsimplexnoise.cpp