Terrain Generator: ConverterNormalizeNode Class Reference
ConverterNormalizeNode Class Reference
#include <normalize.h>
Public Slots
void inputConnectionDeleted (QtNodes::Connection const &connection)
Public Member Functions
ConverterNormalizeNode ()
QString caption () const override
QString name () const override
QWidget * embeddedWidget ()
unsigned int nPorts (QtNodes::PortType port_type) const override
QtNodes::NodeDataType dataType (QtNodes::PortType port_type, QtNodes::PortIndex port_index) const override
QJsonObject save () const override
void restore (QJsonObject const &data) override
std::shared_ptr< QtNodes::NodeData > outData (QtNodes::PortIndex port)
void setInData (std::shared_ptr< QtNodes::NodeData > node_data, QtNodes::PortIndex port)
virtual void created ()
virtual bool hasShared ()
virtual QWidget * sharedWidget ()
Static Public Member Functions
static glm::dvec4 normalize (glm::dvec4 a, glm::dvec4 b)
Private Member Functions
void _generate ()
Private Attributes
bool _set = false
VectorMap _output {1, 1, glm::dvec4{0.00, 0.00, 0.00, 1.00}}
std::shared_ptr< VectorMapData > _input
Friends
class ConverterNormalizeNode_Test
Detailed Description
ConverterNormalizeNode
Node that is used to normalize a vector map, each pixel is normalized.
Constructor & Destructor Documentation
ConverterNormalizeNode()
ConverterNormalizeNode::ConverterNormalizeNode ()
ConverterNormalizeNode
Creates the node. No UI with this one.
Member Function Documentation
_generate()
void ConverterNormalizeNode::_generate () private
_generate
Generates the output data from the supplied and available data.
dataUpdated
Referenced by setInData().
caption()
QString ConverterNormalizeNode::caption () const override
caption
Return a string that is displayed on the node and in the properties.
Returns
QString : The caption.
dataType()
QtNodes::NodeDataType ConverterNormalizeNode::dataType (QtNodes::PortType port_type, QtNodes::PortIndex port_index) const override
dataType
Returns the data type for each of the ports.
Parameters
QtNodes::PortType port_type : The type of port (in or out).
QtNodes::PortIndex port_index : The port index on each side.
Returns
QtNodes::NodeDataType : The type of data the port provides/accepts.
embeddedWidget()
QWidget * ConverterNormalizeNode::embeddedWidget ()
embeddedWidget
Returns a pointer to the widget that gets embedded within the node in the dataflow diagram. (returns nullptr, no widget to manipulate)
Returns
QWidget* : The embedded widget.
inputConnectionDeleted
void ConverterNormalizeNode::inputConnectionDeleted (QtNodes::Connection const & connection) slot
inputConnectionDeleted
Called when an input connection is deleted, this usually resets some data and regenerates the output data.
Parameters
QtNodes::Connection const& connection : The connection being deleted.
dataUpdated
name()
QString ConverterNormalizeNode::name () const override
name
Return a string that is displayed in the node selection list.
Returns
QString : The name.
Referenced by save().
normalize()
glm::dvec4 ConverterNormalizeNode::normalize (glm::dvec4 a, glm::dvec4 b) static
normalize
Normalizes the input a vector.
Parameters
glm::dvec4 a : The vector to be normalized.
glm::dvec4 b : (unused) Extra vector to match requirements for vector map transform function.
Returns
glm::dev4 : The normalized vector.
Referenced by _generate().
nPorts()
unsigned int ConverterNormalizeNode::nPorts (QtNodes::PortType port_type) const override
nPorts
Returns the number of ports the node has per type of port.
Parameters
QtNodes::PortType port_type : The type of port to get the number of ports. QtNodes::PortType::In (input), QtNodes::PortType::Out (output)
Returns
unsigned int : The number of ports.
outData()
std::shared_ptr< QtNodes::NodeData > ConverterNormalizeNode::outData (QtNodes::PortIndex port)
outData
Returns a shared pointer for transport along a connection to another node.
Parameters
QtNodes::PortIndex port : The port to get data from.
Returns
std::shared_ptr<QtNodes::NodeData> : The shared output data.
restore()
void ConverterNormalizeNode::restore (QJsonObject const & data) override
restore
Restores the state of the node from a provided json object. (Nothing to restore, node only works with port data)
Parameters
QJsonObject const& data : The data to restore from.
save()
QJsonObject ConverterNormalizeNode::save () const override
save
Saves the state of the node into a QJsonObject for the system to save to file.
Returns
QJsonObject : The saved state of the node.
setInData()
void ConverterNormalizeNode::setInData (std::shared_ptr< QtNodes::NodeData > node_data, QtNodes::PortIndex port)
setInData
Sets the input data on a port.
Parameters
std::shared_ptr<QtNodes::NodeData> node_data : The shared pointer data being inputted.
QtNodes::PortIndex port : The port the data is being set on.
The documentation for this class was generated from the following files:
src/Nodeeditor/Nodes/normalize.h
src/Nodeeditor/Nodes/normalize.cpp