Terrain Generator: ConverterColorCombineNode Class Reference
ConverterColorCombineNode Class Reference
#include <colorcombine.h>
Public Slots
void inputConnectionDeleted (QtNodes::Connection const &connection)
void redChanged (double value)
void greenChanged (double value)
void blueChanged (double value)
void alphaChanged (double value)
Public Member Functions
ConverterColorCombineNode ()
void created () override
QString caption () const override
QString name () const override
QWidget * embeddedWidget ()
QWidget * sharedWidget ()
unsigned int nPorts (QtNodes::PortType port_type) const override
QtNodes::NodeDataType dataType (QtNodes::PortType port_type, QtNodes::PortIndex port_index) const override
std::shared_ptr< QtNodes::NodeData > outData (QtNodes::PortIndex port)
QJsonObject save () const override
void restore (QJsonObject const &data) override
void setInData (std::shared_ptr< QtNodes::NodeData > node_data, QtNodes::PortIndex port)
virtual bool hasShared ()
Private Member Functions
void _generate ()
Private Attributes
VectorMap _output {1, 1, glm::dvec4{1.00, 1.00, 1.00, 1.00}}
std::shared_ptr< IntensityMapData > _red
std::shared_ptr< IntensityMapData > _green
std::shared_ptr< IntensityMapData > _blue
std::shared_ptr< IntensityMapData > _alpha
double _red_val = 1.00
double _green_val = 1.00
double _blue_val = 1.00
double _alpha_val = 1.00
bool _red_set = false
bool _green_set = false
bool _blue_set = false
bool _alpha_set = false
Ui::ColorCombineNode _ui
Ui::ColorCombineNode _shared_ui
QWidget * _widget
QWidget * _shared_widget
Friends
class ConverterColorCombineNode_Test
Detailed Description
ConverterColorCombineNode
Converter node that combined 4 separate intensity map inputs into a single vector map output. Combining the 4 separate colour channels into a colour output.
Constructor & Destructor Documentation
ConverterColorCombineNode()
ConverterColorCombineNode::ConverterColorCombineNode ()
ConverterColorCombineNode
Creates a converter colour combine node and setups the UI.
Todo:
Long term, fork nodeeditor to include better stylings
Member Function Documentation
_generate()
void ConverterColorCombineNode::_generate () private
_generate
Generates the output data from the supplied and available data.
dataUpdated
Referenced by alphaChanged(), blueChanged(), created(), greenChanged(), inputConnectionDeleted(), redChanged(), and setInData().
alphaChanged
void ConverterColorCombineNode::alphaChanged (double value) slot
alphaChanged
When the alpha spinbox changes we update the data.
Parameters
double value : The new value.
Referenced by created().
blueChanged
void ConverterColorCombineNode::blueChanged (double value) slot
blueChanged
When the blue spinbox changes we update the data.
Parameters
double value : The new value.
Referenced by created().
caption()
QString ConverterColorCombineNode::caption () const override
caption
Return a string that is displayed on the node and in the properties.
Returns
QString : The caption.
created()
void ConverterColorCombineNode::created () override virtual
created
Function is called when the node is created so it can connect to listeners.
dataUpdated
Reimplemented from Node.
dataType()
QtNodes::NodeDataType ConverterColorCombineNode::dataType (QtNodes::PortType port_type, QtNodes::PortIndex port_index) const override
dataType
Returns the data type for each of the ports.
Parameters
QtNodes::PortType port_type : The type of port (in or out).
QtNodes::PortIndex port_index : The port index on each side.
Returns
QtNodes::NodeDataType : The type of data the port provides/accepts.
embeddedWidget()
QWidget * ConverterColorCombineNode::embeddedWidget ()
embeddedWidget
Returns a pointer to the widget that gets embedded within the node in the dataflow diagram.
Returns
QWidget* : The embedded widget.
greenChanged
void ConverterColorCombineNode::greenChanged (double value) slot
greenChanged
When the green spinbox changes we update the data.
Parameters
double value : The new value.
Referenced by created().
inputConnectionDeleted
void ConverterColorCombineNode::inputConnectionDeleted (QtNodes::Connection const & connection) slot
inputConnectionDeleted
Called when an input connection is deleted, this usually resets some data and regenerates the output data.
Parameters
QtNodes::Connection const& connection : The connection being deleted.
name()
QString ConverterColorCombineNode::name () const override
name
Return a string that is displayed in the node selection list.
Returns
QString : The name.
Referenced by save().
nPorts()
unsigned int ConverterColorCombineNode::nPorts (QtNodes::PortType port_type) const override
nPorts
Returns the number of ports the node has per type of port.
Parameters
QtNodes::PortType port_type : The type of port to get the number of ports. QtNodes::PortType::In (input), QtNodes::PortType::Out (output)
Returns
unsigned int : The number of ports.
outData()
std::shared_ptr< QtNodes::NodeData > ConverterColorCombineNode::outData (QtNodes::PortIndex port)
outData
Returns a shared pointer for transport along a connection to another node.
Parameters
QtNodes::PortIndex port : The port to get data from.
Returns
std::shared_ptr<QtNodes::NodeData> : The shared output data.
redChanged
void ConverterColorCombineNode::redChanged (double value) slot
redChanged
When the red spinbox changes we update the data.
Parameters
double value : The new value.
Referenced by created().
restore()
void ConverterColorCombineNode::restore (QJsonObject const & data) override
restore
Restores the state of the node from a provided json object.
Parameters
QJsonObject const& data : The data to restore from.
save()
QJsonObject ConverterColorCombineNode::save () const override
save
Saves the state of the node into a QJsonObject for the system to save to file.
Returns
QJsonObject : The saved state of the node.
setInData()
void ConverterColorCombineNode::setInData (std::shared_ptr< QtNodes::NodeData > node_data, QtNodes::PortIndex port_index)
setInData
Sets the input data on a port.
Parameters
std::shared_ptr<QtNodes::NodeData> node_data : The shared pointer data being inputted.
QtNodes::PortIndex port : The port the data is being set on.
sharedWidget()
QWidget * ConverterColorCombineNode::sharedWidget () virtual
sharedWidget
Returns a pointer to the widget that gets displayed in the properties panel.
Returns
QWidget* : The shared widget.
Reimplemented from Node.
The documentation for this class was generated from the following files:
src/Nodeeditor/Nodes/colorcombine.h
src/Nodeeditor/Nodes/colorcombine.cpp