Terrain Generator: BezierEditWidget Class Reference
BezierEditWidget Class Reference
#include <bezierwidget.h>
Signals
void curveChanged ()
Public Member Functions
BezierEditWidget (int divs=4, QWidget *parent=nullptr)
bool intersect (QLineF line, QPointF *pos)
double valueAt (double value)
std::vector< QPointF > save ()
void restore (std::vector< QPointF > values)
Protected Member Functions
void resizeEvent (QResizeEvent *event)
void mouseMoveEvent (QMouseEvent *event)
void mousePressEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
void enterEvent (QEvent *event)
void leaveEvent (QEvent *event)
void keyPressEvent (QKeyEvent *event)
void mouseDoubleClickEvent (QMouseEvent *event)
Private Member Functions
void _clear ()
Private Attributes
BezierFactory * _factory
std::vector< Bezier > _beziers
QPointF _prev
QGraphicsLineItem * _line_x = nullptr
QGraphicsLineItem * _line_y = nullptr
QGraphicsTextItem * _text_x = nullptr
QGraphicsTextItem * _text_y = nullptr
QGraphicsEllipseItem * _control = nullptr
QGraphicsEllipseItem * _extra_0 = nullptr
QGraphicsEllipseItem * _extra_1 = nullptr
Bezier * _bezier_0 = nullptr
Bezier * _bezier_1 = nullptr
QGraphicsLineItem * _line_start = nullptr
QGraphicsLineItem * _line_end = nullptr
Detailed Description
BezierEditWidget
A custom widget that lets users draw curves and slopes using bezier curves that are constrained to ensure the vertical line test does not fail thus creating a widget that can apply the function y = f(x).
Constructor & Destructor Documentation
BezierEditWidget()
BezierEditWidget::BezierEditWidget (int divs = 4, QWidget * parent = nullptr)
BezierEditWidget
Creates the new bezier editing widget. Sets up the scene and view and creates a basic curve.
Parameters
int divs : The number of section to display for the backround grid. Default is 4 (a 4x4 16 squares grid)
QWidget* parent : The parent housing widget.
Member Function Documentation
_clear()
void BezierEditWidget::_clear () private
_clear
Clears all the bezier curves (for restore).
Referenced by restore().
enterEvent()
void BezierEditWidget::enterEvent (QEvent * event) protected
enterEvent
When the mouse enters the widget the editing controls are shown.
Parameters
QEvent* event : Unused event.
intersect()
bool BezierEditWidget::intersect (QLineF line, QPointF * pos)
intersect
Get the intersection of a line with the entire combined bezier curve. Returns true if the intersection was successful. pos is unchanged if the intersect fails.
Parameters
QLineF line : The line to try and intersect with.
QPointF* pos : The position of the intersection.
Returns
bool : Whether or not the intersection was successful.
Referenced by mouseMoveEvent(), and valueAt().
keyPressEvent()
void BezierEditWidget::keyPressEvent (QKeyEvent * event) protected
keyPressEvent
When the user pressed the X key while hovering over a control point that control point is placed at the exact same spot as its corresponding end point.
Parameters
QKeyEvent* event : The key press event.
leaveEvent()
void BezierEditWidget::leaveEvent (QEvent * event) protected
leaveEvent
When the mouse leaves the widget the control elements are hidden.
Parameters
QEvent* event : Unused event.
mouseDoubleClickEvent()
void BezierEditWidget::mouseDoubleClickEvent (QMouseEvent * event) protected
mouseDoubleClickEvent
When the user double clicks on the widget the bezier curve within the x pos of the click is split calling its split function.
Parameters
QMouseEvent* event : The mouse double click event.
curveChanged
mouseMoveEvent()
void BezierEditWidget::mouseMoveEvent (QMouseEvent * event) protected
mouseMoveEvent
When the mouse is moved, so long as a control element is selected it will be dragged and updating the widget. If the user is not manipulating a control element the widget draws a preview x and y axis showing what the y = f(x) would be along the curve.
Parameters
QMouseEvent *event : The mouse move event.
mousePressEvent()
void BezierEditWidget::mousePressEvent (QMouseEvent * event) protected
mousePressEvent
When the mouse is pressed it the user selects a control point its reference is saved as a pointer (along with any other needed objects) for manipulating the curve.
Parameters
QMouseEvent* event : The mouse press event.
curveChanged
mouseReleaseEvent()
void BezierEditWidget::mouseReleaseEvent (QMouseEvent * event) protected
mouseReleaseEvent
When the mouse button is released the pointers to the control elements being manipulated are set to null, and the curve changed event is emitted to allow for calculations with the curve to begin again.
Parameters
QMouseEvent* event : The mouse release event. (unused)
curveChanged
resizeEvent()
void BezierEditWidget::resizeEvent (QResizeEvent * event) protected
resizeEvent
Resizes the view to fit the widget in the view keeping aspect ratio.
Parameters
QResizeEvent* event : Unused parameter.
restore()
void BezierEditWidget::restore (std::vector< QPointF > values)
restore
Restores the state of the widget with a list of given values that make up the points of the curves.
Parameters
std::vector<QPointF> values : The values of the curve.
Referenced by ConverterBezierCurveNode::created(), and ConverterBezierCurveNode::restore().
save()
std::vector< QPointF > BezierEditWidget::save ()
save
Saves the points of the bezier curve in a std::vector for storage or for use in syncing multilple curves.
Returns
std::vector<QPointF> : A list of points that make up the curve.
Referenced by ConverterBezierCurveNode::created(), and ConverterBezierCurveNode::save().
valueAt()
double BezierEditWidget::valueAt (double value)
valueAt
Get the resutling value as a function of y = f(x). X is clamped between 0 and
The value returned is (soft) expected to be between 0 and 1. Since the control points can go above and below y bounds of 0 and 1 the resulting curve can go beyond those bounds thus an f(x) can produce y values less than 0 or greater than 1 as well as between.
Parameters
double value : The value to transform.
Returns
double : The transformed value.
Referenced by ConverterBezierCurveNode::_generate().
The documentation for this class was generated from the following files:
src/Nodeeditor/Nodes/BezierCurveWidget/bezierwidget.h
src/Nodeeditor/Nodes/BezierCurveWidget/bezierwidget.cpp