Terrain Generator: InputTextureNode Class Reference
InputTextureNode Class Reference
#include <inputtexture.h>
Public Slots
void textureUpdated ()
Public Member Functions
InputTextureNode ()
void created () override
QString caption () const override
QString name () const override
QWidget * embeddedWidget ()
QWidget * sharedWidget ()
unsigned int nPorts (QtNodes::PortType port_type) const override
QtNodes::NodeDataType dataType (QtNodes::PortType port_type, QtNodes::PortIndex port_index) const override
std::shared_ptr< QtNodes::NodeData > outData (QtNodes::PortIndex port)
QJsonObject save () const override
void restore (QJsonObject const &data) override
void setInData (std::shared_ptr< QtNodes::NodeData > node_data, QtNodes::PortIndex port)
virtual bool hasShared ()
Private Slots
void _loadFile ()
void _newFileAccept ()
Private Member Functions
void _setPixmaps ()
Private Attributes
bool _new_file = false
int _new_file_res = 1024
Texture * _texture = nullptr
int _texture_index = -1
Ui::InputTextureNode _ui
Ui::InputTextureNode _shared_ui
Ui::NewTextureDialogue _new_texture_ui
QWidget * _widget
QWidget * _shared
QDialog * _dialogue
Friends
class InputTextureNode_Test
Detailed Description
InputTextureNode
A node for having a drawn (created within the program) texture or a loaded texture from the users system.
Constructor & Destructor Documentation
InputTextureNode()
InputTextureNode::InputTextureNode ()
InputTextureNode
Creates the node and creates the UI.
Member Function Documentation
_loadFile
void InputTextureNode::_loadFile () private slot
_loadFile
Called when the load button is pressed. The user selects an input texture to load into the project.
dataUpdated
Referenced by created().
_newFileAccept
void InputTextureNode::_newFileAccept () private slot
_newFileAccept
Called when the new texture dialogue has been accepted, this will create a new blank texture.
dataUpdated
Referenced by created().
_setPixmaps()
void InputTextureNode::_setPixmaps () private
_setPixmaps
Updates the labels that displays the loaded/created textures.
Referenced by _loadFile(), _newFileAccept(), restore(), and textureUpdated().
caption()
QString InputTextureNode::caption () const override
caption
Return a string that is displayed on the node and in the properties.
Returns
QString : The caption.
created()
void InputTextureNode::created () override virtual
created
Function is called when the node is created so it can connect to listeners.
dataUpdated
Reimplemented from Node.
dataType()
QtNodes::NodeDataType InputTextureNode::dataType (QtNodes::PortType port_type, QtNodes::PortIndex port_index) const override
dataType
Returns the data type for each of the ports.
Parameters
QtNodes::PortType port_type : The type of port (in or out).
QtNodes::PortIndex port_index : The port index on each side.
Returns
QtNodes::NodeDataType : The type of data the port provides/accepts.
embeddedWidget()
QWidget * InputTextureNode::embeddedWidget ()
embeddedWidget
Returns a pointer to the widget that gets embedded within the node in the dataflow diagram.
Returns
QWidget* : The embedded widget.
name()
QString InputTextureNode::name () const override
name
Return a string that is displayed in the node selection list.
Returns
QString : The name.
Referenced by save().
nPorts()
unsigned int InputTextureNode::nPorts (QtNodes::PortType port_type) const override
nPorts
Returns the number of ports the node has per type of port.
Parameters
QtNodes::PortType port_type : The type of port to get the number of ports. QtNodes::PortType::In (input), QtNodes::PortType::Out (output)
Returns
unsigned int : The number of ports.
outData()
std::shared_ptr< QtNodes::NodeData > InputTextureNode::outData (QtNodes::PortIndex port)
outData
Returns a shared pointer for transport along a connection to another node.
Parameters
QtNodes::PortIndex port : The port to get data from.
Returns
std::shared_ptr<QtNodes::NodeData> : The shared output data.
restore()
void InputTextureNode::restore (QJsonObject const & data) override
restore
Restores the state of the node from a provided json object.
Parameters
QJsonObject const& data : The data to restore from.
dataUpdated
save()
QJsonObject InputTextureNode::save () const override
save
Saves the state of the node into a QJsonObject for the system to save to file.
Returns
QJsonObject : The saved state of the node.
setInData()
void InputTextureNode::setInData (std::shared_ptr< QtNodes::NodeData > node_data, QtNodes::PortIndex port)
setInData
Sets the input data on a port.
Parameters
std::shared_ptr<QtNodes::NodeData> node_data : The shared pointer data being inputted.
QtNodes::PortIndex port : The port the data is being set on.
sharedWidget()
QWidget * InputTextureNode::sharedWidget () virtual
sharedWidget
Returns a pointer to the widget that gets displayed in the properties panel.
Returns
QWidget* : The shared widget.
Reimplemented from Node.
textureUpdated
void InputTextureNode::textureUpdated () slot
textureUpdated
Called when the attached texture is updated.
dataUpdated
Referenced by _loadFile(), _newFileAccept(), and restore().
The documentation for this class was generated from the following files:
src/Nodeeditor/Nodes/inputtexture.h
src/Nodeeditor/Nodes/inputtexture.cpp