Terrain Generator: Light Class Reference
Light Class Reference
#include <light.h>
Public Member Functions
QVector3D position ()
float intensity ()
QVector3D color ()
float rotateY (float value)
float rotateX (float value)
float setRotationY (float value)
float setRotationX (float value)
void setIntensity (float value)
void setColor (QVector3D color)
void paintGL (QMatrix4x4 camera, float width, float height)
Private Member Functions
void _clampRotationX ()
Private Attributes
float _rotation_x = 0.0f
float _rotation_y = 0.0f
float _intensity = 1.0f
QVector3D _color {1.0f, 1.0f, 1.0f}
Detailed Description
Light
Class that manages the light value (sun) that is displayed in the opengl widget. Houses position, intensity, color, and direction. Draws the sun onto the widget.
Member Function Documentation
_clampRotationX()
void Light::_clampRotationX () private
_clampRotationX
Clamps the rotation over the terrain between 0 and 90 degrees.
Referenced by rotateX(), and setRotationX().
color()
QVector3D Light::color ()
color
Returns the colour of the light in vector form.
Returns
QVector3D : The light colour.
Referenced by OpenGL::lightColor(), OpenGL::paintGL(), and setColor().
intensity()
float Light::intensity ()
intensity
Return the intensity of the sun.
Returns
float : The intensity of the light.
Referenced by OpenGL::paintGL().
paintGL()
void Light::paintGL (QMatrix4x4 camera, float width, float height)
paintGL
Draws the sun icon and and direction lines onto the opengl widget.
Parameters
QMatrix4x4 camera : The projection and view matrix of the camera.
float width : The width of the viewport.
float height : The height of the viewport.
Referenced by OpenGL::paintGL().
position()
QVector3D Light::position ()
position
Return the position of the sun in the world space.
Returns
QVector3D : The position of the sun.
Referenced by paintGL(), and OpenGL::paintGL().
rotateX()
float Light::rotateX (float value)
rotateX
Rotates the light above the terrain. Rotation is clamped between 0 and 90 degrees.
Parameters
float value : The value to rotate the light by.
Returns
float : The new rotation value.
Referenced by OpenGL::mouseMoveEvent().
rotateY()
float Light::rotateY (float value)
rotateY
Rotates the light around the terrain (turntable).
Parameters
float value : The value to rotate the light by.
Returns
float : The new rotation value.
Referenced by OpenGL::mouseMoveEvent().
setColor()
void Light::setColor (QVector3D color)
setColor
Sets the lights colour.
Parameters
QVector3D color : The color to set the light to.
Referenced by OpenGL::setLightColor().
setIntensity()
void Light::setIntensity (float value)
setIntensity
Sets the light intensity.
Parameters
float value : The value to set the sun intensity.
setRotationX()
float Light::setRotationX (float value)
setRotationX
Sets the rotation over the terrain. This overrides the previous value. Returns the updated rotation value. Rotation is clamped between 0 and 90 degrees.
Parameters
float value : The new value to override with.
Returns
float : The new rotation value.
Referenced by OpenGL::OpenGL(), and OpenGL::sunRotationX().
setRotationY()
float Light::setRotationY (float value)
setRotationY
Sets the rotation around the terrain. This overrides the previous value. Returns the updated rotation value.
Parameters
float value : The new value to override with.
Returns
float : The new rotation value.
Referenced by OpenGL::OpenGL(), and OpenGL::sunRotationY().
The documentation for this class was generated from the following files:
src/OpenGL/light.h
src/OpenGL/light.cpp