Terrain Generator: ConverterErosionNode Class Reference
ConverterErosionNode Class Reference
#include <erosion.h>
Public Slots
void inputConnectionDeleted (QtNodes::Connection const &connection)
Public Member Functions
ConverterErosionNode ()
void created () override
QString caption () const override
QString name () const override
QWidget * embeddedWidget ()
QWidget * sharedWidget ()
unsigned int nPorts (QtNodes::PortType port_type) const override
QtNodes::NodeDataType dataType (QtNodes::PortType port_type, QtNodes::PortIndex port_index) const override
QJsonObject save () const override
void restore (QJsonObject const &data) override
std::shared_ptr< QtNodes::NodeData > outData (QtNodes::PortIndex port)
void setInData (std::shared_ptr< QtNodes::NodeData > node_data, QtNodes::PortIndex port)
virtual bool hasShared ()
Private Member Functions
void _generate ()
void _smooth (int x, int y)
Private Attributes
IntensityMap _output {1, 1, 1.00}
IntensityMap _sediment {1, 1, 0.00}
IntensityMap _erosion {1, 1, 0.00}
std::shared_ptr< IntensityMapData > _input
bool _set = false
int _iterations = 10000
int _max_drop_life = 200
double _inertia = 0.4
double _sediment_capacity = 1.00
double _min_sediment_capacity = 0.01
double _deposit_speed = 0.012
double _erosion_speed = 0.012
double _erosion_radius = 0.2
double _g = 4.00
double _evaporation_rate = 0.12
double _smooth_strength = 0.10
Ui::Erosion _ui
Ui::Erosion_Scroll _shared_ui
QWidget * _widget
QWidget * _shared_widget
Detailed Description
Erosion Node is not quiet accurate enough
NOTE: The flow of the water appears to be correct NOTE: The erosion of the soil appears to be correct NOTE: The sediment of the soil appears to be incorrect
Todo:
FIXME: Incorrect sedimentation NOTE: Evaporation is wrong?
FIXME: See above, may be connected.
ConverterErosionNode
Applies erosion simulation (water and rain) over the provided terrain height map.
Constructor & Destructor Documentation
ConverterErosionNode()
ConverterErosionNode::ConverterErosionNode ()
ConverterErosionNode
Creates the node.
Member Function Documentation
_generate()
void ConverterErosionNode::_generate () private
_generate
Generates the output data from the supplied and available data.
dataUpdated
Referenced by setInData().
_smooth()
void ConverterErosionNode::_smooth (int x, int y) private
_smooth
Applies a smoothing function (kernel) to a pixel at a specific point. Used during the sediment placement process as there is some heavy artifacting. Interesting side effect of this function the way it is, is the changing of the smooth value effects an intensity of the erosion effect.
Parameters
int x : The x pixel to smooth.
int y : The y pixel to smooth.
Referenced by _generate().
caption()
QString ConverterErosionNode::caption () const override
caption
Return a string that is displayed on the node and in the properties.
Returns
QString : The caption.
created()
void ConverterErosionNode::created () override virtual
created
Function is called when the node is created so it can connect to listeners.
Reimplemented from Node.
dataType()
QtNodes::NodeDataType ConverterErosionNode::dataType (QtNodes::PortType port_type, QtNodes::PortIndex port_index) const override
dataType
Returns the data type for each of the ports.
Parameters
QtNodes::PortType port_type : The type of port (in or out).
QtNodes::PortIndex port_index : The port index on each side.
Returns
QtNodes::NodeDataType : The type of data the port provides/accepts.
embeddedWidget()
QWidget * ConverterErosionNode::embeddedWidget ()
embeddedWidget
Returns a pointer to the widget that gets embedded within the node in the dataflow diagram.
Returns
QWidget* : The embedded widget.
inputConnectionDeleted
void ConverterErosionNode::inputConnectionDeleted (QtNodes::Connection const & connection) slot
inputConnectionDeleted
Called when an input connection is deleted, this usually resets some data and regenerates the output data.
Parameters
QtNodes::Connection const& connection : The connection being deleted.
name()
QString ConverterErosionNode::name () const override
name
Return a string that is displayed in the node selection list.
Returns
QString : The name.
Referenced by save().
nPorts()
unsigned int ConverterErosionNode::nPorts (QtNodes::PortType port_type) const override
nPorts
Returns the number of ports the node has per type of port.
Parameters
QtNodes::PortType port_type : The type of port to get the number of ports. QtNodes::PortType::In (input), QtNodes::PortType::Out (output)
Returns
unsigned int : The number of ports.
outData()
std::shared_ptr< QtNodes::NodeData > ConverterErosionNode::outData (QtNodes::PortIndex port)
outData
Returns a shared pointer for transport along a connection to another node.
Parameters
QtNodes::PortIndex port : The port to get data from.
Returns
std::shared_ptr<QtNodes::NodeData> : The shared output data.
restore()
void ConverterErosionNode::restore (QJsonObject const & data) override
restore
Restores the state of the node from a provided json object.
Parameters
QJsonObject const& data : The data to restore from.
save()
QJsonObject ConverterErosionNode::save () const override
save
Saves the state of the node into a QJsonObject for the system to save to file.
Returns
QJsonObject : The saved state of the node.
setInData()
void ConverterErosionNode::setInData (std::shared_ptr< QtNodes::NodeData > node_data, QtNodes::PortIndex port)
setInData
Sets the input data on a port.
Parameters
std::shared_ptr<QtNodes::NodeData> node_data : The shared pointer data being inputted.
QtNodes::PortIndex port : The port the data is being set on.
sharedWidget()
QWidget * ConverterErosionNode::sharedWidget () virtual
sharedWidget
Returns a pointer to the widget that gets displayed in the properties panel.
Returns
QWidget* : The shared widget.
Reimplemented from Node.
The documentation for this class was generated from the following files:
src/Nodeeditor/Nodes/erosion.h
src/Nodeeditor/Nodes/erosion.cpp