Terrain Generator: VectorMapData Class Reference
VectorMapData Class Reference
#include <pixmap.h>
Public Member Functions
VectorMapData ()
VectorMapData (VectorMap const &vector_map)
QtNodes::NodeDataType type () const override
VectorMap vectorMap () const
Private Attributes
VectorMap _vector_map
Detailed Description
VectorMapData
Class that wraps an vector map for transport between nodes in a connection
Constructor & Destructor Documentation
VectorMapData() [1/2]
VectorMapData::VectorMapData ()
VectorMapData
Creates a new vector map data.
VectorMapData() [2/2]
VectorMapData::VectorMapData (VectorMap const & vector_map)
VectorMapData
Creates a new vector map data using the provided vector map.
Parameters
IntenistyMap const& vector_map : The housed vector map.
Member Function Documentation
type()
QtNodes::NodeDataType VectorMapData::type () const override
type
Returns the type that the container is. This is used to determine what ports can accept this data and the label on those ports.
Returns
QtNodes::NodeDataType : The type of data this is.
Referenced by ConverterNormalizeNode::dataType(), ConverterColorSplitNode::dataType(), OutputNode::dataType(), InputConstantVectorNode::dataType(), ConverterVectorIntensityNode::dataType(), ConverterColorCombineNode::dataType(), ConverterVectorDotNode::dataType(), InputTextureNode::dataType(), ConverterVectorMathNode::dataType(), and InputSimplexNoiseNode::dataType().
vectorMap()
VectorMap VectorMapData::vectorMap () const
vectorMap
Returns the housed vector map.
Returns
VectorMap : The vector map.
The documentation for this class was generated from the following files:
src/Nodeeditor/Datatypes/pixmap.h
src/Nodeeditor/Datatypes/pixmap.cpp