Terrain Generator: Bezier Class Reference
Bezier Class Reference
#include <bezierwidget.h>
Public Member Functions
Bezier ()
Bezier (QPen l_pen, QPen c_pen, QBrush c_brush, QPen e_pen, QBrush e_brush, QPen cu_pen, float r, float c_thick, float l_width, float c_width, QPointF c_0, QPointF c_1, QGraphicsEllipseItem *e_0, QGraphicsEllipseItem *e_1, QGraphicsScene *s)
bool intersect (QLineF line, QPointF *pos)
void draw ()
void hide ()
void show ()
void clear ()
void remove (bool keep_ellipses=false)
Bezier * split ()
Public Attributes
QPen line_pen
QPen control_pen
QBrush control_brush
QPen end_pen
QBrush end_brush
QPen curve_pen
float radius
float control_thick
float line_width
float curve_width
std::vector< QGraphicsLineItem * > curve
QGraphicsScene * scene = nullptr
QGraphicsEllipseItem * end_0 = nullptr
QGraphicsEllipseItem * end_1 = nullptr
QGraphicsEllipseItem * control_0 = nullptr
QGraphicsEllipseItem * control_1 = nullptr
QGraphicsLineItem * line_0 = nullptr
QGraphicsLineItem * line_1 = nullptr
Detailed Description
Bezier
The container that houses a single segment of the overall bezier curve. This manages the two end points, the two control points, the two lines betwen them, and the curve itself.
Constructor & Destructor Documentation
Bezier() [1/2]
Bezier::Bezier ()
Bezier
Creates a new bezier curve with all the default values used.
Bezier() [2/2]
Bezier::Bezier (QPen l_pen, QPen c_pen, QBrush c_brush, QPen e_pen, QBrush e_brush, QPen cu_pen, float r, float c_thick, float l_width, float c_width, QPointF c_0, QPointF c_1, QGraphicsEllipseItem * e_0, QGraphicsEllipseItem * e_1, QGraphicsScene * s)
Bezier
Creates a new bezier with the overriden values.
Parameters
QPen l_pen : The line pen (between control and end point).
QPen c_pen : The control pen (outline on a control circle).
QBrush c_brush : The control brush (fill).
QPen e_pen : The end point pen (outline).
QBrush e_brush : The end point brush (fill).
QPen cu_pen : The curve pen (the bezier curve itself)
float r : The radius of the control and end point circles.
float c_thick : The control and end point outline thickness.
float l_width : The width of the lines between control and end point.
float c_width : The width of the lines that make up the curve.
QPointF c_0 : The first control point location.
QPointF c_1 : The second control point location.
QGraphicsEllipseItem* e_0 : The pointer to the firstend point (end points are shared between beziers)
QGraphicsEllipseItem* e_1 : The pointer to the second end point.
QGraphicsScene* s : The scene that draws the elements
Member Function Documentation
clear()
void Bezier::clear ()
clear
Clears the drawn lines from the scene, usually used for redrawing the updated curve.
Referenced by draw(), remove(), and split().
draw()
void Bezier::draw ()
draw
Draws the curve using the bezier function to draw segments of line to the scene.
Referenced by Bezier(), BezierEditWidget::mouseMoveEvent(), and BezierEditWidget::mousePressEvent().
hide()
void Bezier::hide ()
hide
Hides the control elements from the scene.
intersect()
bool Bezier::intersect (QLineF line, QPointF * pos)
intersect
Get the intersection point of a line through the bezier curve. If the line does not intersect with the curve false is return and pos is unchanged.
Parameters
QLineF line : The line to try to intersect with.
QPointF* pos : The position where the intersection could happen.
Returns
bool : Whether the line intersects or not.
remove()
void Bezier::remove (bool keep_ellipses = false)
remove
Removes the control elements from the scene (end points and ellipses). If the inputted flag is set to true the end points are not removed (used for splitting a curve).
Parameters
bool keep_ellipses : Whether or not to keep the end points.
show()
void Bezier::show ()
show
Shows the control elements in the scene.
Referenced by split().
split()
Bezier * Bezier::split ()
split
Splits a bezier curve into two smaller connected bezier curves. It does not accurately match the original.
Returns
Bezier* : A list of two bezier curves [Bezier, Bezier].
Todo:
Make the split two bezier curves accurately represent the original curve.
The documentation for this class was generated from the following files:
src/Nodeeditor/Nodes/BezierCurveWidget/bezierwidget.h
src/Nodeeditor/Nodes/BezierCurveWidget/bezierwidget.cpp