Terrain Generator: ConverterBezierCurveNode Class Reference
ConverterBezierCurveNode Class Reference
#include <bezier.h>
Public Slots
void inputConnectionDeleted (QtNodes::Connection const &connection)
Public Member Functions
ConverterBezierCurveNode ()
void created () override
QString caption () const override
QString name () const override
QWidget * embeddedWidget ()
QWidget * sharedWidget ()
unsigned int nPorts (QtNodes::PortType port_type) const override
QtNodes::NodeDataType dataType (QtNodes::PortType port_type, QtNodes::PortIndex port_index) const override
std::shared_ptr< QtNodes::NodeData > outData (QtNodes::PortIndex port)
QJsonObject save () const override
void restore (QJsonObject const &data) override
void setInData (std::shared_ptr< QtNodes::NodeData > node_data, QtNodes::PortIndex port)
virtual bool hasShared ()
Private Member Functions
void _generate ()
Private Attributes
IntensityMap _output {1, 1, 1.00}
std::shared_ptr< IntensityMapData > _input
bool _set = false
BezierEditWidget * _widget
BezierEditWidget * _shared_widget
Detailed Description
ConverterBezierCurveNode
Node that displays a complex slope and curve editing widget used for adjusting values as a function of f(x).
Converts an intensity map value x into a new intensity value x' with a function f(x) that is defined by a series of curves and slopes created in the widget. The x value is calculated via finding the vertical line intercept on the line segments of the slopes.
Constructor & Destructor Documentation
ConverterBezierCurveNode()
ConverterBezierCurveNode::ConverterBezierCurveNode ()
ConverterBezierCurveNode
Creates a bezier curve node and creates the control widgets.
Member Function Documentation
_generate()
void ConverterBezierCurveNode::_generate () private
_generate
Generates the output data from the supplied and available data.
dataUpdated
Referenced by created(), and setInData().
caption()
QString ConverterBezierCurveNode::caption () const override
caption
Return a string that is displayed on the node and in the properties.
Returns
QString The caption.
created()
void ConverterBezierCurveNode::created () override virtual
created
Function is called when the node is created so it can connect to listeners.
Reimplemented from Node.
dataType()
QtNodes::NodeDataType ConverterBezierCurveNode::dataType (QtNodes::PortType port_type, QtNodes::PortIndex port_index) const override
dataType
Returns the data type for each of the ports.
Parameters
QtNodes::PortType port_type : The type of port (in or out).
QtNodes::PortIndex port_index : The port index on each side.
Returns
QtNodes::NodeDataType : The type of data the port provides/accepts.
embeddedWidget()
QWidget * ConverterBezierCurveNode::embeddedWidget ()
embeddedWidget
Returns a pointer to the widget that gets embedded within the node in the dataflow diagram.
Returns
QWidget* : The embedded widget.
inputConnectionDeleted
void ConverterBezierCurveNode::inputConnectionDeleted (QtNodes::Connection const & connection) slot
inputConnectionDeleted
Called when an input connection is deleted, this usually resets some data and regenerates the output data.
Parameters
QtNodes::Connection const& connection : The connection being deleted.
dataUpdated
name()
QString ConverterBezierCurveNode::name () const override
name
Return a string that is displayed in the node selection list.
Returns
QString : The name.
Referenced by save().
nPorts()
unsigned int ConverterBezierCurveNode::nPorts (QtNodes::PortType port_type) const override
nPorts
Returns the number of ports the node has per type of port.
Parameters
QtNodes::PortType port_type : The type of port to get the number of ports. QtNodes::PortType::In (input), QtNodes::PortType::Out (output)
Returns
unsigned int : The number of ports.
outData()
std::shared_ptr< QtNodes::NodeData > ConverterBezierCurveNode::outData (QtNodes::PortIndex port)
outData
Returns a shared pointer for transport along a connection to another node.
Parameters
QtNodes::PortIndex port : The port to get data from.
Returns
std::shared_ptr<QtNodes::NodeData> : The shared output data.
restore()
void ConverterBezierCurveNode::restore (QJsonObject const & data) override
restore
Restores the state of the node from a provided json object.
Parameters
QJsonObject const& data : The data to restore from.
save()
QJsonObject ConverterBezierCurveNode::save () const override
save
Saves the state of the node into a QJsonObject for the system to save to file.
Returns
QJsonObject : The saved state of the node.
setInData()
void ConverterBezierCurveNode::setInData (std::shared_ptr< QtNodes::NodeData > node_data, QtNodes::PortIndex port)
setInData
Sets the input data on a port.
Parameters
std::shared_ptr<QtNodes::NodeData> node_data : The shared pointer data being inputted.
QtNodes::PortIndex port : The port the data is being set on.
sharedWidget()
QWidget * ConverterBezierCurveNode::sharedWidget () virtual
sharedWidget
Returns a pointer to the widget that gets displayed in the properties panel.
Returns
QWidget* : The shared widget.
Reimplemented from Node.
The documentation for this class was generated from the following files:
src/Nodeeditor/Nodes/bezier.h
src/Nodeeditor/Nodes/bezier.cpp