Terrain Generator: ConverterVectorDotNode Class Reference
ConverterVectorDotNode Class Reference
#include <vectordot.h>
Public Slots
void inputConnectionDeleted (QtNodes::Connection const &connection)
void x0Changed (double value)
void y0Changed (double value)
void z0Changed (double value)
void w0Changed (double value)
void x1Changed (double value)
void y1Changed (double value)
void z1Changed (double value)
void w1Changed (double value)
Public Member Functions
ConverterVectorDotNode ()
void created () override
QString caption () const override
QString name () const override
QWidget * embeddedWidget ()
QWidget * sharedWidget ()
unsigned int nPorts (QtNodes::PortType port_type) const override
QtNodes::NodeDataType dataType (QtNodes::PortType port_type, QtNodes::PortIndex port_index) const override
std::shared_ptr< QtNodes::NodeData > outData (QtNodes::PortIndex port)
QJsonObject save () const override
void restore (QJsonObject const &data) override
void setInData (std::shared_ptr< QtNodes::NodeData > node_data, QtNodes::PortIndex port_index)
virtual bool hasShared ()
Private Member Functions
void _generate ()
Static Private Member Functions
static double dot (glm::dvec4 a, glm::dvec4 b)
Private Attributes
IntensityMap _output {1, 1, 1.00}
std::shared_ptr< VectorMapData > _in_0
std::shared_ptr< VectorMapData > _in_1
glm::dvec4 _in_val_0 {1.00, 1.00, 1.00, 1.00}
glm::dvec4 _in_val_1 {1.00, 1.00, 1.00, 1.00}
bool _in_set_0 = false
bool _in_set_1 = false
Ui::VectorDotProduct _ui
Ui::VectorDotProduct _shared_ui
QWidget * _widget
QWidget * _shared_widget
Friends
class ConverterVectorDotNode_Test
Detailed Description
ConverterVectorDotNode
Node that converts two vector map inputs into an intensity map using dot product.
Constructor & Destructor Documentation
ConverterVectorDotNode()
ConverterVectorDotNode::ConverterVectorDotNode ()
ConverterVectorDotNode
Creates the node and the UI.
Member Function Documentation
_generate()
void ConverterVectorDotNode::_generate () private
_generate
Generates the output data from the supplied and available data.
dataUpdated
Referenced by created(), inputConnectionDeleted(), restore(), setInData(), w0Changed(), w1Changed(), x0Changed(), x1Changed(), y0Changed(), y1Changed(), z0Changed(), and z1Changed().
caption()
QString ConverterVectorDotNode::caption () const override
caption
Return a string that is displayed on the node and in the properties.
Returns
QString : The caption.
created()
void ConverterVectorDotNode::created () override virtual
created
Function is called when the node is created so it can connect to listeners.
Reimplemented from Node.
dataType()
QtNodes::NodeDataType ConverterVectorDotNode::dataType (QtNodes::PortType port_type, QtNodes::PortIndex port_index) const override
dataType
Returns the data type for each of the ports.
Parameters
QtNodes::PortType port_type : The type of port (in or out).
QtNodes::PortIndex port_index : The port index on each side.
Returns
QtNodes::NodeDataType : The type of data the port provides/accepts.
dot()
double ConverterVectorDotNode::dot (glm::dvec4 a, glm::dvec4 b) static private
dot
Algorithm for applying the vector dot product to the two vectors.
Parameters
glm::dvec4 a : The first vector.
glm::dvec4 b : The second vector.
Returns
double : The resulting value.
Referenced by _generate().
embeddedWidget()
QWidget * ConverterVectorDotNode::embeddedWidget ()
embeddedWidget
Returns a pointer to the widget that gets embedded within the node in the dataflow diagram.
Returns
QWidget* : The embedded widget.
inputConnectionDeleted
void ConverterVectorDotNode::inputConnectionDeleted (QtNodes::Connection const & connection) slot
inputConnectionDeleted
Called when an input connection is deleted, this usually resets some data and regenerates the output data.
Parameters
QtNodes::Connection const& connection : The connection being deleted.
name()
QString ConverterVectorDotNode::name () const override
name
Return a string that is displayed in the node selection list.
Returns
QString : The name.
Referenced by save().
nPorts()
unsigned int ConverterVectorDotNode::nPorts (QtNodes::PortType port_type) const override
nPorts
Returns the number of ports the node has per type of port.
Parameters
QtNodes::PortType port_type : The type of port to get the number of ports. QtNodes::PortType::In (input), QtNodes::PortType::Out (output)
Returns
unsigned int : The number of ports.
outData()
std::shared_ptr< QtNodes::NodeData > ConverterVectorDotNode::outData (QtNodes::PortIndex port)
outData
Returns a shared pointer for transport along a connection to another node.
Parameters
QtNodes::PortIndex port : The port to get data from.
Returns
std::shared_ptr<QtNodes::NodeData> : The shared output data.
restore()
void ConverterVectorDotNode::restore (QJsonObject const & data) override
restore
Restores the state of the node from a provided json object.
Parameters
QJsonObject const& data : The data to restore from.
save()
QJsonObject ConverterVectorDotNode::save () const override
save
Saves the state of the node into a QJsonObject for the system to save to file.
Returns
QJsonObject : The saved state of the node.
setInData()
void ConverterVectorDotNode::setInData (std::shared_ptr< QtNodes::NodeData > node_data, QtNodes::PortIndex port_index)
setInData
Sets the input data on a port.
Parameters
std::shared_ptr<QtNodes::NodeData> node_data : The shared pointer data being inputted.
QtNodes::PortIndex port : The port the data is being set on.
sharedWidget()
QWidget * ConverterVectorDotNode::sharedWidget () virtual
sharedWidget
Returns a pointer to the widget that gets displayed in the properties panel.
Returns
QWidget* : The shared widget.
Reimplemented from Node.
w0Changed
void ConverterVectorDotNode::w0Changed (double value) slot
w0Changed
Called to updated the first vector when the w value changed.
Parameters
double value : The new value.
Referenced by created().
w1Changed
void ConverterVectorDotNode::w1Changed (double value) slot
w1Changed
Called to updated the second vector when the w value changed.
Parameters
double value : The new value.
Referenced by created().
x0Changed
void ConverterVectorDotNode::x0Changed (double value) slot
x0Changed
Called to updated the first vector when the x value changed.
Parameters
double value : The new value.
Referenced by created().
x1Changed
void ConverterVectorDotNode::x1Changed (double value) slot
x1Changed
Called to updated the second vector when the x value changed.
Parameters
double value : The new value.
Referenced by created().
y0Changed
void ConverterVectorDotNode::y0Changed (double value) slot
y0Changed
Called to updated the first vector when the y value changed.
Parameters
double value : The new value.
Referenced by created().
y1Changed
void ConverterVectorDotNode::y1Changed (double value) slot
y1Changed
Called to updated the second vector when the y value changed.
Parameters
double value : The new value.
Referenced by created().
z0Changed
void ConverterVectorDotNode::z0Changed (double value) slot
z0Changed
Called to updated the first vector when the z value changed.
Parameters
double value : The new value.
Referenced by created().
z1Changed
void ConverterVectorDotNode::z1Changed (double value) slot
z1Changed
Called to updated the second vector when the z value changed.
Parameters
double value : The new value.
Referenced by created().
The documentation for this class was generated from the following files:
src/Nodeeditor/Nodes/vectordot.h
src/Nodeeditor/Nodes/vectordot.cpp