name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Install required packages
      run: sudo apt-get update && sudo apt-get upgrade && sudo apt-get install graphviz plantuml doxygen
      
    - name: Build
      run: pushd docs &>/dev/null && ./build.sh --wiki && popd &>/dev/null
      
    - name: Deploy Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs/source_code/html

    - name: Diploy Wiki
      uses: SwiftDocOrg/github-wiki-publish-action@v1
      with:
        path: assets/help
      env:
        GH_PERSONAL_ACCESS_TOKEN:  ${{ secrets.GH_REPO_WIKI_DEPLOY }}
