name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Install required packages
      run: sudo apt-get update && sudo apt-get upgrade && sudo apt-get install plantuml doxygen
      
    - name: Build
      run: pushd docs &>/dev/null && ./build.sh && popd &>/dev/null
      
    - name: Deploy Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/source_code/html

    - name: Diploy Wiki
      uses: SwiftDocOrg/github-wiki-publish-action@v1
      with:
        path: assets/help
      env:
        GH_PERSONAL_ACCESS_TOEK:  ${{ secrets.GH_REPO_WIKI_DEPLOY }}
